### ISSUE TITLE
There is no way to stop Global services

### ISSUE THREAD

**Issue by ivankristianto** [10up/wp-local-docker-v2#1]
When I check with `docker ps` I can see the global services still up and running even I don't have any other environment run.
And I see we have the function ready:
https://github.com/10up/wp-local-docker-v2/blob/master/src/gateway.js#L140
but we just don't have it available to call from command line.

**Comment by cmmarslender** [comment]
`10updocker stop all` is the correct command to do this. It will first stop all environments, then turn off all the global services.

I added a bit to the docs on the [global commands](https://10up.github.io/wp-local-docker-docs/global-commands/) page to make this info easier to find.
