### ISSUE TITLE
The image hitwe/phpmemcachedadmin has been removed

### ISSUE THREAD

**Issue by imgerson** [10up/wp-local-docker-v2#100]
**Describe the bug**
It looks like the image hitwe/phpmemcachedadmin has been removed.

https://hub.docker.com/u/hitwe
https://hub.docker.com/r/hitwe/phpmemcachedadmin/

**Steps to Reproduce**
```
10updocker create testing-deleted-image.com
```

This will produce:
```
Pulling memcacheadmin (hitwe/phpmemcachedadmin:v2.0.2)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling memcacheadmin (hitwe/phpmemcachedadmin:v2.0.2)...
ERROR: pull access denied for hitwe/phpmemcachedadmin, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Expected behavior**
The only solution here is to replace `phpmemcachedadmin`.

Thanks! 10updocker rocks 🚀

**Comment by tcmulder** [comment]
I'm experiencing the same issue. Is replacing `phpmemcachedadmin` something that I can do myself, or do I need to wait for an official patch and update 10updocker after? Note that I'm pretty new to both Docker and 10updocker, so I apologize if the answer should be obvious.

**Comment by tylercherpak** [comment]
Docker image `'hitwe/phpmemcachedadmin:v2.0.2' ` is no longer available and has been removed in the latest version of wp-local-docker.
If you are running into issues on existing provisioned sites you can resolve these issues by editing the `/config/docker-compose.yml` and the nginx configs ( `/config/nginx/default.conf ` `/config/nginx/develop.conf `)
Remove these lines from the docker-compose.yml file:
```
  memcacheadmin:
    image: 'hitwe/phpmemcachedadmin:v2.0.2'
    expose:
      - '80'
    depends_on:
      - memcached 
```
Remove these lines from the nginx confs:
```
    location /__memcacheadmin/ {
        rewrite ^/__memcacheadmin/(.*) /$1 break;
        proxy_pass http://memcacheadmin:80;
    }
```

Let us know if you are still having issues!

**Comment by tcmulder** [comment]
I updated wp-local-docker and it's all working now—thanks!

**Comment by imgerson** [comment]
Problem solved 🎉 !
