### ISSUE TITLE
Cannot start global dns service after upgrading to 2.7.0

### ISSUE THREAD

**Issue by aaemnnosttv** [10up/wp-local-docker-v2#107]
**Describe the bug**

After upgrading to the latest release 2.7.0 from 2.6.2, starting global services fails.

```
Ensuring global network exists
 - Creating network
Ensuring global cache volume exists
 - Creating Volume
Ensuring global services are running
Creating global_dns_1         ... error
Creating global_gateway_1 ... 
Creating global_mysql_1   ... 
Creating global_gateway_1     ... done
Creating global_mysql_1       ... done
Creating global_mailcatcher_1 ... done
Creating global_phpmyadmin_1  ... done

ERROR: for dns  Cannot start service dns: Ports are not available: port is already allocated.
ERROR: Encountered errors while bringing up the project.
(node:57238) UnhandledPromiseRejectionWarning: Error: Command failed: docker-compose up -d
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at startGateway (/Users/aaemnnosttv/.nvm/versions/node/v10.16.3/lib/node_modules/wp-local-docker/src/gateway.js:94:9)
    at Object.startGlobal (/Users/aaemnnosttv/.nvm/versions/node/v10.16.3/lib/node_modules/wp-local-docker/src/gateway.js:119:11)
(node:57238) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:57238) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to Reproduce**
1. Attempt to start a local environment
1. See `dns` fail to start due to port conflict

**Environment information**
```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	8-Core Intel Core i9
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	8
  L2 Cache (per Core):	256 KB
  L3 Cache:	16 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
```

**Additional context**
I tried stopping all docker containers and restarting Docker as well but it continued to fail with the same error when starting.

I checked for running processes on [port `53`](https://github.com/10up/wp-local-docker-v2/blob/d787b32aa036ffdc9c4afdabfbb7ffc57ed8bc6a/global/docker-compose.yml#L11-L12) but found none.

I wasn't able to get it to work on 2.7.0 so I had to rollback to 2.6.2.

**Comment by dustinrue** [comment]
You have something that is listening on that port. You might try restarting your machine, brew services list. You can test for a locally running DNS server by issuing `host google.com 127.0.0.1`. If it responds then you have something listening to port 53 locally.

If you're unable to determine what is listening you can install 2.7.0 again, run `10updocker configure` (follow all default prompts) and then edit the resulting ~/.wplocaldocker/global/docker-compose.yml file. Edit the file and change the listening address for the dnsmasq container by removing the 127.0.0.1 portion of it leaving it to just the ports. Start a site and it will work like it did in the previous version.

**Comment by jamesmorrison** [comment]
@dustinrue I use DNSmasq locally to point *`.test` to `127.0.0.1`; I had to remove the:

```
    ports:
        - "127.0.0.1:53:53/udp"
        - "127.0.0.1:53:53"
```

section entirely to get this working on 2.7.0 (after upgrading from 2.6.2).

**Comment by aaemnnosttv** [comment]
@dustinrue I had `dnsmasq` running installed via Homebrew. I tried stopping this originally and it reported to stop successfully but after checking it again it had not been stopped and requires `sudo` to stop.

After stopping the service, local docker is working no problem now after upgrading 👍
