### ISSUE TITLE
Upgrade breaks when using a custom PHP-FPM image

### ISSUE THREAD

**Issue by cdwieber** [10up/wp-local-docker-v2#111]
**Describe the bug**
I had modified the docker-compose.yml file to use a custom php-fpm image in order to run some performance profiling with Blackfire, and this has broken the upgrade 2.6.0 => 2.7.0. Granted, this is unintended usage, and the short-term solution is to simply revert to the default provided `docker-compose.yml` but nonetheless I've been asked to document the issue in case we want to support such configurations in the future.

When running `npm update -g wp-local-docker` and then `10updocker update` in the file, the output for this particular project is exactly as follows: 
```
Locating project files for mainetoday-test
Locating project files for mainetoday-test
Stopping docker containers for mainetoday-test
Stopping mainetoday-test_nginx_1         ... done
Stopping mainetoday-test_phpfpm_1        ... done
Stopping mainetoday-test_memcacheadmin_1 ... done
Stopping mainetoday-test_memcached_1     ... done
Stopping mainetoday-test_elasticsearch_1 ... done
Stopping mainetoday-test_blackfire_1     ... done
Removing mainetoday-test_nginx_1         ... done
Removing mainetoday-test_phpfpm_1        ... done
Removing mainetoday-test_memcacheadmin_1 ... done
Removing mainetoday-test_memcached_1     ... done
Removing mainetoday-test_elasticsearch_1 ... done
Removing mainetoday-test_blackfire_1     ... done
Removing network mainetoday-test_default
Network wplocaldocker is external, skipping

Created backup of previous configuration mainetoday-test
Locating project files for mainetoday-test
Finished updating mainetoday-test
Copying required files...
(node:20440) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at upgradeEnvTwoDotSix (/Users/chris/.nvm/versions/node/v13.2.0/lib/node_modules/wp-local-docker/src/environment.js:272:51)
(node:20440) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20440) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to Reproduce**
1. In the project directory, use the docker-compose.yml file here: https://gist.github.com/cdwieber/5361e70af4f021cd026217acd97d687d
2. In the build step, it's referencing this php-fpm Dockerfile as modified thusly: https://gist.github.com/cdwieber/b56ac326f7726175f7adecea081d648c
3. Run `npm update -g wp-local-docker` and then `10updocker update` in the project.

**Expected behavior**
Upgrade proceeds as intended.

**Environment information**
 - Device: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
- OS: macOS Catalina 10.15.3
 - WordPress version: 5.4
- Node Version: 10.0.0 & 13.2.0 (tested on both, managed w/ nvm)

**Comment by tylercherpak** [comment]
upgrade commands are only entended for default wp-local-docker images, closing out this issue. Let us know if you have questions. Thanks
