### ISSUE TITLE
VaultPress Import Failing

### ISSUE THREAD

**Issue by rickalee** [10up/wp-local-docker-v2#117]
When trying to import a VaultPress backup from a VIP Go Multisite single site in via Sequel Pro or WP CLI - I get multiple errors due to default values.

Examples from postmeta and links table respectively:
BLOB, TEXT, GEOMETRY or JSON column 'meta_value' can't have a default value
BLOB, TEXT, GEOMETRY or JSON column 'link_notes' can't have a default value

This appears to be related to mysql configuration/mode issue.
https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_strict_trans_tables
https://dev.mysql.com/doc/refman/5.7/en/data-type-defaults.html

Updated /.wplocaldocker/global/config/mysql/config.cnf to include:
sql-mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION" and restarted container to no affect. 

Due to the size of backups - I can only open the .sql files via [Hex Fiend](https://ridiculousfish.com/hexfiend/) to modify CREATE statement as a workaround on part of tables.

**Comment by rickalee** [comment]
Found workaround for this by using https://wordpress.org/plugins/wp-migrate-db/ and importing one table at a time. Took a couple hours for a large site but it worked.

**Comment by JayWood** [comment]
Setting the following at the top of the SQL file worked for me.
`SET SQL_MODE='ALLOW_INVALID_DATES';`

To do this with multiple files you could probably do something like this:
`$ echo "SET SQL_MODE='ALLOW_INVALID_DATES';" | cat - *.sql > combined.sql` 

To save on opening the large file you could then: `$ head combined.sql`

My config location was different, located at `/usr/local/lib/node_modules/wp-local-docker/global/config/mysql` I'll see if I can resolve this at a later date. For now, this is what worked for me.

**Comment by dustinrue** [comment]
Can you tell me what version of MySQL is reported at the top of the backup file?

**Comment by rickalee** [comment]
@dustinrue No sign of MySQL version in VaultPress export. Checking Site Health Info on VIP Go site reveal this. 


Extension | mysqli
Server version | 10.2.15-MariaDB-log
Client version | mysqlnd 5.0.12-dev - 20150407 
Table prefix | wp_
Database charset | utf8mb4
Database collation | utf8mb4_general_ci

**Comment by tylercherpak** [comment]
Hey @rickalee Is this still an issue on the latest version of wp-local-docker? Let me know if you have any questions! Thanks 😄

**Comment by tylercherpak** [comment]
Hey all,

I am going to close this issue but if you are still having issues let us know and we will reopen this issue. Thanks!
