### ISSUE TITLE
Update official supported Node version to v12 LTS

### ISSUE THREAD

**Issue by nicholasio** [10up/wp-local-docker-v2#121]
**Is your enhancement related to a problem? Please describe.**
Currently, the docs say that we only support Node 10. While Node 10 is still LTS, it is not the current LTS version. The current LTS version is Node 12.

**Describe the solution you'd like**
Update the official support version of Node 12 to stay ahead and make sure the tool remains compatible with the most recent LTS version.

I have been using wp local docker with Node 12 for a little while and haven't had any issues. So I think we're safe to just update the official supported version to 12.

Additionally, I suggest we add a .nvmrc to explicitly declared the node version for those using nvm (only applicable for those developing wp-local-docker) and also explicitly set the node version in package.json (`engines` property).

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by eugene-manuilov** [comment]
Looks like we need to include this into the next `2.8.0` release since we have seen issues with node `10.0.0` during testing the `2.8.0-rc.2` version.

**Comment by eugene-manuilov** [comment]
It has been implemented and merged via #123. We can consider this ticket as done.
