### ISSUE TITLE
Add a command to list all local environments

### ISSUE THREAD

**Issue by stefano-b** [10up/wp-local-docker-v2#122]
I think it would be useful to have a command to list all existent local environments, maybe something like `10updocker list` or `10updocker ls`; ideally this should list all environments and maybe their status (started/stopped) and their URL (some terminal emulators let you click on URLs, this would be useful to easily go to the site).

**Comment by eugene-manuilov** [comment]
It has been implemented and merged via #133, #134 and #137. We can consider this ticket as done.
