### ISSUE TITLE
Error: '/var/www/html/' is not writable by current user

### ISSUE THREAD

**Issue by allysonsouza** [10up/wp-local-docker-v2#124]
**Versions**

- Fedora 32
- WP Local Docker 2.7.0
- Docker version 19.03.11, build 42e35e6
- docker-compose version 1.25.4, build unknown

**Describe your question**

I'm unable to create a site, always getting this error:

```
Downloading WordPress
Error: '/var/www/html/' is not writable by current user.
(node:7975) UnhandledPromiseRejectionWarning: Error: Command failed: docker-compose exec phpfpm wp core download --force
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at Object.download (/usr/local/lib/node_modules/wp-local-docker/src/wordpress.js:9:5)
    at async createEnv (/usr/local/lib/node_modules/wp-local-docker/src/create.js:417:13)
    at async Object.command (/usr/local/lib/node_modules/wp-local-docker/src/create.js:471:13)
    at async init (/usr/local/lib/node_modules/wp-local-docker/index.js:67:13)
(node:7975) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7975) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by dustinrue** [comment]
This usually happens if you delete the environment and recreate it but don't actually destroy it using 10updocker delete. When you don't use delete the containers remain running which causes this issue. Restart docker on your system and then start the env again

**Comment by allysonsouza** [comment]
I tried to delete the environment, restart docker service and then recreate it, but I got the same result.

**Comment by tylercherpak** [comment]
Hey @allysonsouza 

Are you still have this issue? Can you test on the latest version `3.0.0`? Thanks! 😄

**Comment by tylercherpak** [comment]
Hey @allysonsouza 

We haven't heard back from you so I am going to close this ticket but feel free to comment if you are still having this issue and we can reopen it. Thanks!

**Comment by tomalec** [comment]
I got the same effect for creating a new env with Ubuntu 22
```
docker version 20.10.18
Docker Desktop 4.12.0 (85629)
docker-compose version 1.28.4, build cabd5cfb
```

for running `10updocker create` for a completely new env

**Comment by tomalec** [comment]
@tylercherpak Would you mind reopening the issue? It's still the case for the environment mentioned above.
