### ISSUE TITLE
Single quotes added to filename on wp-cli db import/export.

### ISSUE THREAD

**Issue by allysonsouza** [10up/wp-local-docker-v2#125]
**Describe the bug**
When I export a database, the filename is created enclosed by single quotes: `'db.sql'`. For importing it only works with the single quotes arround the filename and extension too.

**Steps to Reproduce**

1. Run `10updocker wp export {dbfilename}.sql`

**Expected behavior**
It's expected to have your database exported without single quotes around the filename, and to be able to import databases without adding single quotes too.

**Environment information**
 - Device: Desktop Computer
 - OS: Windows 10 Pro 19041.329

**Comment by eugene-manuilov** [comment]
Hi @allysonsouza. Thanks for reporting this issue. Could you please confirm that you have used `wp db export {dbfilename}.sql` and not just `wp export {dbfilename}.sql` since it's two different commands?

**Comment by allysonsouza** [comment]
Hi @eugene-manuilov,

I've mistyped the command in the issue, but I was typing it correctly, `wp db export`. Look at the printscreen:
![image](https://user-images.githubusercontent.com/2000638/89596802-9ea61080-d82e-11ea-84fe-1802a61114ec.png)

And it generated a file called `'db.sql'`, as I said previously.

**Comment by nicholasio** [comment]
This is not an issue for me with wp-local-docker@next, noting that I'm using Docker for Windows with WSL 2 integration.

**Comment by eugene-manuilov** [comment]
Thanks @nicholasio!

@allysonsouza can you install `@next` version and try again? Just run `npm i -g wp-local-docker@next` and it will install `2.8.0-rc.8` or later, then run your command again. Please, let me know if it works or not.

**Comment by allysonsouza** [comment]
Thanks @nicholasio and @eugene-manuilov, I tested here and the problem is solved in the `@next` version.

**Comment by eugene-manuilov** [comment]
Awesome, @allysonsouza! Please, keep in mind that `@next` means it's not ready yet to be published as a new stable version. So, use it at your risk or downgrade to the current stable version.
