### ISSUE TITLE
"Error: No widgets deleted." on 10updocker create results in fatal error

### ISSUE THREAD

**Issue by jamesmorrison** [10up/wp-local-docker-v2#128]
**Describe the bug**

I set up a new install where there was an existing DB (set up by 10updocker previously), as part of the "remove default content" process, there was a failed attempt to remove widgets:

```
Warning: Widget 'search-2' doesn't exist.
Warning: Widget 'recent-posts-2' doesn't exist.
Warning: Widget 'recent-comments-2' doesn't exist.
Warning: Widget 'archives-2' doesn't exist.
Warning: Widget 'categories-2' doesn't exist.
Warning: Widget 'meta-2' doesn't exist.
Error: No widgets deleted.
(node:21941) UnhandledPromiseRejectionWarning: Error: Command failed: docker-compose exec phpfpm wp widget delete search-2 recent-posts-2 recent-comments-2 archives-2 categories-2 meta-2
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at Object.emptyContent (/Users/10up/.nvm/versions/node/v12.18.2/lib/node_modules/wp-local-docker/src/wordpress.js:68:5)
    at async createEnv (/Users/10up/.nvm/versions/node/v12.18.2/lib/node_modules/wp-local-docker/src/create.js:427:13)
    at async Object.command (/Users/10up/.nvm/versions/node/v12.18.2/lib/node_modules/wp-local-docker/src/create.js:471:13)
    at async init (/Users/10up/.nvm/versions/node/v12.18.2/lib/node_modules/wp-local-docker/index.js:67:13)
(node:21941) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21941) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to Reproduce**

1. Create 10updocker install
2. Ensure that "remove default content": yes
3. Remove folder from sites directory
4. Create 10updocker install with same name as step 1
5. Ensure that "remove default content": yes
6. Error above appears

**Expected behavior**

There should be a graceful exit of this process, moving onto the next task.

**Environment information**
 - Device: MacBook Pro
 - OS: MacOS 10.15.6
 - Browser and version: iTerm 2 (ZSH)
 - WordPress version: 5.4.2
 - Plugins and version: None
 - Theme and version: WP_DEFAULT_THEME
 - Node 12.8.2 / NPM 6.14.5 (but also tested with same result on Node 10.21.0 / NPM 6.14.4

**Comment by jayhill90** [comment]
I'm also running into this. I'm sure it's because I didn't use 10updocker delete to delete the environment originally. I've even restarted Docker a few times and still run into this trying to make a new site. I've removed all my containers as well at one point today.

**Comment by tylercherpak** [comment]
hey everyone 👋 

I am going to close this issue since this should be resolved in the latest release. If you are still having issues feel free to reopen the issue. Thanks! 😄
