### ISSUE TITLE
Add command or flag to stop all 10updocker containers.

### ISSUE THREAD

**Issue by jmichaelward** [10up/wp-local-docker-v2#129]
**Is your enhancement related to a problem? Please describe.**
As a user, when I run `10updocker stop <environment>`, the containers for a particular environment are stopped, but global containers continue running. There is not currently a command to stop 10updocker services entirely. The current alternative is to stop containers individually or stop all containers using `docker stop $(docker ps -a -q)`.

**Describe the solution you'd like**
I'd like to see either a flag, such as `10updocker stop --all`, or a separate command, such as `10updocker shutdown`, which stops all containers started by 10updocker.

**Additional context**
It's sometimes necessary to run several different development environments, because each of them has their strengths. Laravel Valet, for instance, makes it dead simple to quickly and easily get an environment up and running with little hassle, as it uses the resources of your local environment. MAMP makes it easy to switch between versions of PHP, and between Nginx and Apache, as needed. In an agency setting, sometimes particular clients necessitate particular environments, and being able to switch between them as you work on different projects is paramount.

As such, having a simple command that simply "turns off" 10updocker makes it easier to context switch for those that need to.

**Comment by eugene-manuilov** [comment]
Hey @jmichaelward 

there is already a one for it, just run `10updocker stop all` and it will stop all containers including global ones.

**Comment by jmichaelward** [comment]
Ah well, derp, there it is right there in the documentation. My apologies, I clearly overlooked it.
