### ISSUE TITLE
Symlinking appears impossible

### ISSUE THREAD

**Issue by royscheeren** [10up/wp-local-docker-v2#142]
**Describe your question**

I'm trying to symlink a plugin I want to start working to the plugins folder of the WP environment I've created with wp-local-docker but WP does not seem to be picking it up in the admin panel.

I've used the following command on Mac OS 

```
ln -s DEV_PATH/wordpress/plugins/pluginname ~/wp-local-docker-sites/mysite-test/wordpress/wp-content/plugins/pluginname
```

Terminal seems to pick it up just fine but WP does not. 

Does anyone know what I'md doing wrong?

**Comment by royscheeren** [comment]
Solved it by adding an extra volume in the docker-compose.yml that gets generated on site creation. 
Works for my use case.

**Comment by achchu93** [comment]
Though it is an easy help, I have attached an screenshot for more easy. You have to put that under both `phpfm` and `nginx` volumes. putting under `phpfm` will show you in admin plugins and putting under `nginx` will serve the assets.

You must create the symlink too.

![Screenshot 2023-05-04 at 23 11 25](https://user-images.githubusercontent.com/7522970/236285876-52b4e287-acf9-4e62-867b-efd7e15bbcbc.png)
