### ISSUE TITLE
[2.8.0-rc.7] - CLI Output cosmetic issue.

### ISSUE THREAD

**Issue by nicholasio** [10up/wp-local-docker-v2#145]
**Describe the bug**
There's a cosmetic issue with the CLI output when starting environments.

**Steps to Reproduce**

1. 10updocker start envName

**Expected behavior**
The text would be contained in the box.

**Screenshots**
![image](https://user-images.githubusercontent.com/6104632/89890765-4b272000-dbaa-11ea-8abc-a2dac27f765f.png)

**Environment information**
WSL 2, Windows Terminal, running ZSH

**Additional context**

**Comment by eugene-manuilov** [comment]
@nicholasio it has been fixed and can be tested by installing `@next` version. Run `npm i -g wp-local-docker@next` and it will install `2.8.0-rc.8` which contains a fix for this issue. Could you please try it on your end and let me know how it works now?

**Comment by nicholasio** [comment]
confirmed this is fixed in `2.8.0-rc.8`

**Comment by eugene-manuilov** [comment]
Awesome! Thanks @nicholasio!
