### ISSUE TITLE
[2.8.0-rc.8] New enviroment creation fails with SSL cert error

### ISSUE THREAD

**Issue by nicholasio** [10up/wp-local-docker-v2#147]
**Describe the bug**
New environment creation fails with SSL cert error. I'm effectively unable to create new environments, Due to this error it also does not add the newly created env to the list of environments.

**Steps to Reproduce**
Create a new enviroment.

**Expected behavior**
I'm able to create a new environment, even without SSL certificate.

I suggest handling possible errors due to SSL cert install and falling back to an env without it.

**Screenshots**
2.8.0-rc.8
![image](https://user-images.githubusercontent.com/6104632/90006832-0bc30700-dc70-11ea-8acf-68cf1c7d4162.png)

**Environment information**
 - Device: PC
 - OS:  Windows 10 Pro Insider Preview 20185.1000
 - Docker for Desktop with WSL 2 Integration

**Additional context**

**Comment by eugene-manuilov** [comment]
@nicholasio `2.8.0-rc.9` has been published with `@next` tag. Could you please try it on your end and let me know if it fixes this issue?

**Comment by nicholasio** [comment]
@eugene-manuilov It worked but I don't think SSL certs are working when I use https it says the server closed the connection.

**Comment by eugene-manuilov** [comment]
Yes, that's expected because wp-local-docker can't create a SSL certificate for you due to permission issues. If it can't create certificates, wp-local-docker fallbacks to HTTP version and creates non-secure environment.

By the way, do you know why you have permission issues? Shouldn't config folder be writable or you ran wp-local-docker under a different user?

**Comment by nicholasio** [comment]
@eugene-manuilov no idea about the permission issue. I suspect it's an edge case with my set up (WSL 2 in WIndows). I'm not running docker under a different user. I'm using nvm and installed it globally.

I have seen this happen on Linux environments before, where permissions of the host system weren't properly set in the docker container.

**Comment by felipeelia** [comment]
FWIW, I'm on Linux (Mint) and had that same problem (the folder owner was "root" instead of my user).

**Comment by eugene-manuilov** [comment]
Ok, it looks like a user error. I think we can consider this ticket as complete. Going to close it. Feel free to open a new one if you still need help.
