### ISSUE TITLE
Reconfigure domains after creation?

### ISSUE THREAD

**Issue by jayhill90** [10up/wp-local-docker-v2#150]
**Describe your question**
Is it possible to reconfigure the domains a site responds to after creation? I need to add the www subdomain as the project I'm working on keeps wanting to load under that instead of the root domain like it's suppose to and was just curious if there's a way to add more domains after the fact.

**Comment by eugene-manuilov** [comment]
Hi @jayhill90!

You can run search-replace command to update your current domain in WordPress and `10updocker-hosts add` to add one more domain to your `/etc/hosts` file.

```sh-session
10updocker wp search-replace "http://mysite.test" "http://www.mysite.test"
```
```sh-session
10updocker-hosts add www.mysite.test
```

**Comment by jayhill90** [comment]
Worked perfectly adding the domain with 10updocker-hosts add. Thanks @eugene-manuilov
