### ISSUE TITLE
develop.conf pointing to incorrect root?

### ISSUE THREAD

**Issue by mattonomics** [10up/wp-local-docker-v2#159]
**Describe the bug**
When configuring a container to use the develop version of WordPress, the `develop.conf` file is pointing the root to `/var/www/html/build` though a `wp-config.php` file is being created in `/var/www/html/src`. This causes an unexpected WordPress setup screen to appear when the new URL is opened in a browser.

**Steps to Reproduce**

1. Create a new container and select the develop version of WordPress
2. Open `~/wp-local-docker-sites/your-site/config/nginx/default.conf` and `~/wp-local-docker-sites/your-site/config/nginx/develop.conf` in a text editor. Note that `develop.conf` has set `root /var/www/html/build;`
3. Open `~/wp-local-docker-sites/your-site/wordpress/build` and note there is no `wp-config.php` file.
4. Open `~/wp-local-docker-sites/your-site/wordpress/src` and note that the `wp-config.php` file was created there.

**Expected behavior**
The config file should either point to `~/wp-local-docker-sites/your-site/wordpress/src` (which means the install script would need to install WP dependencies) _or_ the install script should be adjusted to account for a config file being created in `~/wp-local-docker-sites/your-site/wordpress/build` (note it may also need to account for the WP build process).

**Environment information**
 - Device: MacBook Pro (13-inch, 2020)
 - OS: macOS Catalina 10.15.7
 - wp-local-docker-v2 2.7.0

**Additional context**
It may be necessary to comment out the memcache lines in the `develop.conf` file. I didn't have the time to investigate but those were causing everything to 503 despite numerous restarts and such.

**Comment by eugene-manuilov** [comment]
@mattonomics thanks for reporting this issue. We have a new version that solves this issue but requires a few more steps to set up the core development version on a local machine. Can you help us to test it?

Just install the `@next` version using `npm i -g wp-local-docker@next` command and make sure that `10updocker --version` shows `2.8.0-rc.14` or higher. Then create a new environment with `10updocker new` command and follow instructions when it finishes.

Let me know if it works on your end or you see something that can be improved there.

**Comment by jeffpaul** [comment]
@mattonomics any chance you can help test per the comment above?

**Comment by eugene-manuilov** [comment]
Ok, closing this ticket. The new version has been released and it should fix this problem.
