### ISSUE TITLE
List out all environments at localhost

### ISSUE THREAD

**Issue by Viper007Bond** [10up/wp-local-docker-v2#16]
As a quick way to get to any environment's domain, it'd be cool if they were all listed out at http://localhost/ along with their online/offline status.

**Comment by ChaosExAnima** [comment]
@Viper007Bond - For what it's worth, I'd recommend checking out [DockStation](https://dockstation.io/) if you'd like a GUI for listing Docker projects.

**Comment by Viper007Bond** [comment]
I have Kitematic already as recommended by Docker, but that's more about managing images.

`10up/nginx-proxy` is already rendering content at `localhost` so it seems like that could be taken advantage of for WP-Local-Docker specific stuff.

**Comment by eugene-manuilov** [comment]
The next version `2.8.0` will include a command (`10updocker list`) to list all environments with URLs, online/offline statuses and home directories. There is a ticket for it: #122. GUI interface requires a lot of efforts and is something that we consider but don't know exactly when its can be done.

**Comment by eugene-manuilov** [comment]
It has been implemented and merged via #133, #134 and #137. We can consider this ticket as done.
