### ISSUE TITLE
Documentation and new command to automate upgrading PHP version on an existing project

### ISSUE THREAD

**Issue by jeffpaul** [10up/wp-local-docker-v2#164]
**Is your enhancement related to a problem? Please describe.**
From conversation with @TheLastCicada @eugene-manuilov:
There is no documentation on the preferred way to upgrade the PHP version on an existing project.  It is not that obvious because it will require rebuilding the PHP image using a new base image with desired version, would also likely entail introducing a new command that can automate it on the user behalf.

**Describe the solution you'd like**
Mostly described in section above, though more details can be added via comments on this issue.

**Designs**
n/a

**Describe alternatives you've considered**
Avoid new command and simply document all the steps needed?

**Additional context**
n/a

**Comment by tylercherpak** [comment]
https://github.com/10up/wp-local-docker-v2/pull/255 pr to address this. 😄
