### ISSUE TITLE
zsh issue

### ISSUE THREAD

**Issue by cinghaman** [10up/wp-local-docker-v2#166]
I just upgraded to macOS Zsh on the terminal and my 10updocker stopped working, which was working properly before I did that.
I tried to reinstall again but in vain.

I had to revert my terminal to bash to have it working.

Is there documentation to make 10updocker work on zsh? or any pointers to change settings/configs to be able to run it on zsh.
Thanks

**Comment by eugene-manuilov** [comment]
Hi, @cinghaman! Looks like zsh doesn't have NPM binaries folder in its $PATH variable. What do you see when you run `echo $PATH` in your zsh shell?

**Comment by tylercherpak** [comment]
Hey @cinghaman I am closing this issue out, feel free to reopen if you are still having the issue. Thanks! 😄
