### ISSUE TITLE
Release version 2.8.0

### ISSUE THREAD

**Issue by jeffpaul** [10up/wp-local-docker-v2#174]
This issue is for tracking changes for the 2.8.0 release.  Target release date: **TBD**.

### [Release steps](https://github.com/10up/wp-local-docker-v2/blob/master/CONTRIBUTING.md#release-instructions)
- [x] Branch: Starting from `develop`, cut a release branch named `release/2.8.0` for your changes.
- [x] Version bump: Bump the version number in `package.json`, `package-lock.json`, `global/docker-compose.yml`, and any other relevant files if it does not already reflect the version being released.
- [x] Changelog: Add/update the changelog in `CHANGELOG.md`.
- [x] Props: update `CREDITS.md` file with any new contributors, confirm maintainers are accurate.
- [x] Readme updates: Make any other readme changes to `README.md` as necessary.
- [ ] Merge: Make a non-fast-forward merge from your release branch to `develop` (or merge the Pull Request), then do the same for `develop` into `master` (`git checkout master && git merge --no-ff develop`).  `master` contains the stable development version.
- [ ] Push: Push your `master` branch to GitHub (e.g. `git push origin master`).
- [ ] Release: Create a [new release](https://github.com/10up/wp-local-docker-v2/releases/new), naming the tag and the release with the new version number, and targeting the `master` branch.  Paste the changelog from `CHANGELOG.md` into the body of the release and include a link to the [closed issues on the milestone](https://github.com/10up/wp-local-docker-v2/milestone/6?closed=1).  The release should now appear under [releases](https://github.com/10up/wp-local-docker-v2/releases).
- [ ] Close milestone: Edit the [milestone](https://github.com/10up/wp-local-docker-v2/milestone/6) with release date (in the `Due date (optional)` field) and link to GitHub release (in the `Description field`), then close the milestone.
- [ ] Punt incomplete items: If any open issues or PRs which were milestoned for `2.8.0` do not make it into the release, update their milestone to `2.9.0` or `Future Release`.

**Comment by jeffpaul** [comment]
Noting that there isn't a `develop` branch and that we're currently branched off `master`, so will come back post-release to create a `develop` branch, set `develop` as the default branch, and then rebase any existing PRs to `develop`.

**Comment by jeffpaul** [comment]
Noting that we should likely amend the release instructions to ensure the docs repo is updated with any relevant changes in a release.

**Comment by eugene-manuilov** [comment]
@jeffpaul done!

**Comment by jeffpaul** [comment]
I've created a `develop` branch and set that as default and have added some branch protection rules for `master` and `develop`.  I've also updated the release instructions, so looks like we're all set.  Thanks @eugene-manuilov, great work!
