### ISSUE TITLE
Update stuck while updating to 2.8.0

### ISSUE THREAD

**Issue by dhanendran** [10up/wp-local-docker-v2#177]
**Describe the bug**
While updating to 2.8.0, update getting stuck during the process.

**Steps to Reproduce**
1. Update `wp-local-docker` to 2.8.0 with sudo command in mac
2. Fix `EACCES` error if it shows up 
3. See the process stuck in there and not complete

**Expected behavior**
It should update to 2.8.0 version

**Screenshots**
![Screenshot 2021-01-27 at 7 30 10 PM](https://user-images.githubusercontent.com/6737105/106002546-46faaa80-60d7-11eb-89f6-c7c122f38eef.png)

**Environment information**
 - Device: MacBook
 - OS: MacOs Big Sur 11.1

**Comment by eugene-manuilov** [comment]
@dhanendran thanks for logging this issue. Could you please install the `@issue177` version and tell me if it helps to solve your issue?

```
npm i -g wp-local-docker@issue177
```

**Comment by dhanendran** [comment]
Release [2.8.1](https://github.com/10up/wp-local-docker-v2/releases/tag/2.8.1 ) fixed the issue, thanks @eugene-manuilov
