### ISSUE TITLE
Multisite config removed when configuring create to remove default content.

### ISSUE THREAD

**Issue by colegeissinger** [10up/wp-local-docker-v2#182]
**Describe the bug**

I was trying to create a new Subdirectory Multisite with 2.8.1 and noticed after successful creation that the multisite configurations in wp-config.php were not there, resulting in a single site install. After some testing the culprit is around the "Do you want to remove the default content?" entree of the creation process. If I say yes, the multisite configurations will be removed along with it.

Saying no to remove default content will give me a multisite install in the end, which is okay for my use case at the moment, but not something I expected to see.

**Steps to Reproduce**

1. Create a new environment with `10up-local-docker create`
2. Use all the defaults in the create steps but specifically set "Subdirectory Multisite" as the installation type and say Yes to remove the default content.
3. Once create is complete, view the wp-config.php
4. No multisite definitions are set to enable multisite.

**Expected behavior**
Expected to see multisite configurations in wp-config.php

**Screenshots**
[CLI screenshot](https://cloudup.com/cpxsy3s1ECY)
[wp-config.php](https://cloudup.com/cVvMKQXTEkF)

**Environment information**
 - Device: MacBook Pro
 - OS: macOS Catalina 10.15.7
 - Browser and version: n/a
 - WordPress version: 5.6.1
 
 - Plugins and version: n/a
 - Theme and version: n/a
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by colegeissinger** [comment]
An update here, I ran some more tests and actually even though I said **No** to remove default content, I still didn't get the multsite configurations added to wp-config.php. 

In my use case just now I have a proxy set for the media assets and also installed Elasticsearch.

**Comment by eugene-manuilov** [comment]
Hm... it's weird... I can't reproduce this issue on my end. I have tried all possible combinations and all works well for me. 

Which version of node.js do you use? Not sure if this can help, but just in case...

**Comment by colegeissinger** [comment]
This may be an issue centered on my computer. I was having many struggles with WP Local Docker yesterday. Eventually, connections were getting refused after a bit. I shut down my computer and suddenly everything appears to be working as expected now? I've created a few sites this morning and the multisite configurations are now being set! :wat:

My computer has been giving me odd issues like this off and on so this may not be an issue with this software. I think you are probably good to close this as now I can't duplicate this same issue.

**Comment by eugene-manuilov** [comment]
That's awesome! Thanks for letting us know, @colegeissinger!
