### ISSUE TITLE
Uncaught Error: Call to undefined function deine()

### ISSUE THREAD

**Issue by jperks-mower** [10up/wp-local-docker-v2#186]
Hello,

I am trying to import a database .sql file using the command `10updocker wp db import mysql.sql` however I receive the following error message when running the command:

```
jperks@SYR-JPERKS-M21 wordpress % 10updocker wp db import mysql.sql
PHP Fatal error:  Uncaught Error: Call to undefined function deine() in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1197) : eval()'d code:58
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1197): eval()
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1158): WP_CLI\Runner->load_wordpress()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#5 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#6 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#7 {main}
  thrown in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1197) : eval()'d code on line 58
```

It appears that something is trying to call `deine()`, which is perhaps a mistyped `define()`.

**Steps to Reproduce**

1. Run `10updocker wp db import {file}.sql`

**Expected behavior**
To import the database without issue

**Environment information**
 - Device: Macbook
 - OS: MacOS 11.2.3
 - Browser and version: N/A
 - WordPress version: Latest

**Additional context**
The problem started after defining a custom wp-content directory location in docker-compose.yml

**Comment by tylercherpak** [comment]
👋 Hi @jperks-mower are you still having this issue? Is the `mysql.sql` in the root of the wordpress directory? If not where is it located?

**Comment by jperks-mower** [comment]
Hi @tylercherpak . Thanks for getting back to me on this. I don't believe this issue is still happening but if it comes up again I'll report back. Thank you!
