### ISSUE TITLE
10updocker create fail because user format XXXX/me

### ISSUE THREAD

**Issue by margotpaon** [10up/wp-local-docker-v2#187]
Hello everyone! Well I'm having trouble creating an environment with 10updocker create

What is this here

 Error: no such image: wp-php-fpm-dev-7.3-XXX \ margot: invalid reference format: repository name must be lowercase

The user of this computer has this format and I cannot change it

Does anybody know how to solve this? Thank you very much

**Comment by eugene-manuilov** [comment]
@margotpaon, which domain name did you use for your environment?

**Comment by margotpaon** [comment]
puga.test to local env

**Comment by tylercherpak** [comment]
hey @margotpaon This issue has been resolved in the latest release. You can update by run `npm i -g wp-local-docker`. Let us know if you have any questions or still seeing this issue. 😄
