### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by JayWood** [10up/wp-local-docker-v2#190]
**Is your enhancement related to a problem? Please describe.**
* No

**Describe the solution you'd like**
* Allow PHP 8 Support using the available 10up/wp-php-fpm 8.0 image.

**Designs**
* None currently happy to open a quick PR though.

**Describe alternatives you've considered**
* Running my own docker setup, though I like the automation of 10up docker better for personal projects.

**Additional context**
I've been working with PHP 8 a lot lately and it's really grown on me. However, I noticed 10up Docker doesn't currently have PHP 8 support. So I started looking through the source. I figured, hey, why not see if I can get it running, but I ran into a bit of an issue.

I see that there are [constants available](https://github.com/10up/wp-local-docker-v2/blob/d864ebb3f8eba23662b05a55d482a2f2be3cb646/src/commands/create/inquirer.js#L4) in the script which reference PHP versions. Thinking that'd be an easy change I wanted to dig a bit deeper. I unearthed where the [docker-compose is created](https://github.com/10up/wp-local-docker-v2/blob/e2f14c5d8be20cdde92646dbd75fa0b567db7df3/src/commands/create/make-docker-compose.js#L48) and found that the images in use are [10up images only](https://github.com/10up/wp-local-docker-v2/blob/e2f14c5d8be20cdde92646dbd75fa0b567db7df3/src/docker-images.js#L9) ( for php-fpm ). This should be a pretty quick edit, but I'm unsure how stable the [8.0 tagged image](https://hub.docker.com/r/10up/wp-php-fpm/tags?page=1&ordering=last_updated&name=8.0) is, wondering if @dustinrue can weigh in?

**Comment by rcstr** [comment]
I was about to open the same issue 💯
