### ISSUE TITLE
Issue with certificates

### ISSUE THREAD

**Issue by samimakela** [10up/wp-local-docker-v2#192]
We are experiencing issues with the certificates added in 2.8.0.

We've updated wp-local-docker to it's newest version 2.8.1, but it seems that the certificate is not working. 

The .crt and .key files referenced in the .config.json file seem to be ok. We've also checked that the CA can be found in the OS X keychain.

When opening the site with chrome we see `NET::ERR_CERT_AUTHORITY_INVALID`

When viewing the certificate "Internet Widgits Pty Ltd" is shown as the issuer.

Are there any manual steps that we might be missing?

**Comment by eugene-manuilov** [comment]
@samimakela try to run `10updocker cert install` to install CA root on your local machine. Then try to regenerate certificates for your environment using `10updocker cert generate <domain1> <domain2> ...` (not sure if it's really needed, but it won't heart if you update your certs anyway).

If it still doesn't work after running these commands, try to install [mkcert](https://github.com/FiloSottile/mkcert) (that's what wp-local-docker uses under the hood) on your local and run `mkcert -install`. I believe it will give you more details if your computer needs to install something additional.

**Comment by samimakela** [comment]
Thank you for the quick answer, @eugene-manuilov!

The CA seems to be installed just fine and also the certificates are generated. I think the issue is with the server and it’s configuration.

Since mkcert only generates the certificates, but does not configure the server to use them, I tried to look through the source code, but I could not find where nginx is configured to use the generated certificates.

**Comment by eugene-manuilov** [comment]
Certificates are used by nginx-proxy which is located in the global docker-compose config. If you open `~/.wplocaldocker/global/docker-compose.yml` file, then you should see the following line there (it mounts certs directory to the appropriate location in the nginx-proxy container): https://github.com/10up/wp-local-docker-v2/blob/3e0efb3f41a50f17addb31a56a0204ab22c6ebfe/global/docker-compose.yml#L22

When nginx-proxy receives a request from your browser, it finds the corresponding nginx container in your environments using the `VIRTUAL_HOST` environment variable defined for an nginx container. Then nginx-proxy uses the `CERT_NAME` environment variable defined for the same nginx container to figure out which certificate to use. That's how it works in a nutshell.

Check your global and environment configs to make sure you have it configured correctly.

**Comment by samimakela** [comment]
Thanks @eugene-manuilov. Of course! That's why the global services needed a restart after updating to version 2.8.x. 

```10updocker stop all```
```10updocker start```

Thank you very much for your help!

**Comment by tylercherpak** [comment]
Hey everyone, I think this has been resolved so I am going to close this issue. If you are still experiencing issues. Feel free to reopen! 😄
