### ISSUE TITLE
Cannot access webstite URL, 503 error

### ISSUE THREAD

**Issue by sharp2448** [10up/wp-local-docker-v2#193]
**Describe the bug**

When I start using wp local docker cca 3 months ago, everything was fine except SSL (I didn't care about SSL so I just commented 443 port). But recently I added a new website and cleared cache and since then I'm having this problem.
**But anyway I don't think the problem is with my setup. Because now I reinstall OS and I'm having exactly the same issue again.** 
All services are running and logs seem to be OK

Cannot access a website. 
Without HTTP version http://test-dev-wp.test I'm getting:
(screenshot below)

> 503 Service Temporarily Unavailable

With HTTPS  https://test-dev-wp.test :
(screenshot below)

> Secure Connection Failed

An error occurred during a connection to test-dev-wp.test. PR_END_OF_FILE_ERROR

**Steps to Reproduce**

1. Install fresh 10updocker with `npm install -g wp-local-docker`
2. Create environment with `10updocker create` command
2. Follow instructions and create single wordpres site fx `test-dev-wp.test` 
3. Wait till finish and try to access website
4. Logs:   [nginx container](https://pastebin.com/embed_js/SPPgisHy?theme=dark)
                [10up/nginx-proxy](https://pastebin.com/embed_js/VZyLG7pr?theme=dark)
                [wp-php-fpm-dev-7.4](https://pastebin.com/embed_js/6Yc9gAz5?theme=dark)

**Expected behavior**

Be able at least access not secure (HTTP) version.

**Screenshots**

![docker services](https://user-images.githubusercontent.com/30528303/114266262-9de50000-99f5-11eb-8f73-db2525e22545.png)
![SSl-error](https://user-images.githubusercontent.com/30528303/114266263-9faec380-99f5-11eb-8d93-fde62e5919ac.png)
![503error](https://user-images.githubusercontent.com/30528303/114266266-a2111d80-99f5-11eb-8f65-9630fde20641.png)

**Environment information**
 - Device: ThinkPad W520
 - OS: Arch Linux, Kernel: 5.10.28-1-lts 
 - Browser and version:  Firefox 87.0, Chromium 89.0.4389.114
 - WordPress version: 5.7
 

**Additional context**

**Comment by gebeer** [comment]
Exactly same issue here 
Arch Linux
npm v14.15.3

https connections used to work under npm 10.0.0 and wp-local-docker@2.7.0

**Comment by azatecas** [comment]
I was setting up 10updocker on Fedora 34 and ran across the same issue. I tried debugging it for hours and reinstalled it a bunch of things. However i ended up trying the #188 10updocker on m1 solution and it worked. I edited  the ~/.wplocaldocker/global/docker-compose.yml file and change the gateway from 10up/nginx-proxy to 10up/nginx-proxy:multiarch and mysql:5 to image: mariadb and it started working. I honestly have no idea why it worked but give it a shot

**Comment by smcnally** [comment]
tyvm, @azatecas. Your suggested ```docker-compose.yml``` updates also worked for me.

> in ```~/.wplocaldocker/global/docker-compose.yml```
change ```gateway``` from 
    ```10up/nginx-proxy``` 
    to 
    ```10up/nginx-proxy:multiarch```
    and 
    ```mysql:5```
    to 
    ```image: mariadb```

This was weird troubleshooting and the first time running into it with 10updocker.

![image](https://user-images.githubusercontent.com/850878/141594515-f7cc5de8-15a1-4f0a-a575-39899dd1288f.png)

**Environment information**

    Device: Precision M6600
    OS: Ubuntu, Kernel: FredTheBeast 5.13.0-21-generic #21-Ubuntu SMP 
    Browser and version: Firefox 94.0    
    WordPress version: 5.8.2

**Comment by smcnally** [comment]
> This was weird troubleshooting and the first time running into it with 10updocker.

"weird troubleshooting" as Issues from folks running M1 chips kept surfacing. Filling out the **Environment information** reminded me I'm on an SMP kernel and perhaps nginx needs multiarch. I'm also running docker / 10updocker on a non-LTS flavor (U21.10) for the first time.

**Comment by tylercherpak** [comment]
Hey everyone 👋 We have much better support for ARM architecture in the latest release. Can you try installing the latest version `3.0.0` with `npm i -g wp-local-docker` and let me know if you are still having this issue?

I recommend taking a backup of `~/.wplocaldocker/global/docker-compose.yml` file and then run `10updocker configure` and accept the default configuration to use the new docker images that support M1 and ARM much better.

**Comment by tylercherpak** [comment]
Going to close this one since I haven't heard back but if you are still having issues feel free to comment and I will open it back up! Thanks all!
