### ISSUE TITLE
10updocker clone ssh issue

### ISSUE THREAD

**Issue by tylercherpak** [10up/wp-local-docker-v2#196]
**Describe the bug**
Running  `10updocker clone git@git-url` on a private repo returns: 
```
Error: Failed to retrieve list of SSH authentication methods: Failed getting response
Error : An error occurred during cloning your repository. Please, submit a new issue: https://github.com/10up/wp-local-docker-v2/issues
```

**Steps to Reproduce**

Use clone command on a private repo.

**Environment information**
 - Device:  MacBook
 - OS:  MacOS 11.2.3

**Comment by TheLastCicada** [comment]
Same issue on my local

**Comment by TheLastCicada** [comment]
This also happens with a public repo on Github:

```
% 10updocker clone git@github.com:eugene-manuilov/woocommerce.git
Error: Failed to retrieve list of SSH authentication methods: Failed getting response

 Error : An error occurred during cloning your repository. Please, submit a new issue: https://github.com/10up/wp-local-docker-v2/issues
```

**Comment by jasondewitt** [comment]
i ran into this problem too, im thinking the git clone running through the 10updocker tool is either not respecting the ssh config file i have locally or doesnt have access to the ssh keys. I was able to work around it by cloning over https

**Comment by tylercherpak** [comment]
closing since we removed the clone cmd and `nodegit`
