### ISSUE TITLE
CLI reports v2.1.38 is available

### ISSUE THREAD

**Issue by ChaosExAnima** [10up/wp-local-docker-v2#2]
Hi there!

Looks like there's a bug happening. It seems that NPM [believes](https://www.npmjs.com/package/wp-local-docker) the latest version is 2.1.38, yet the latest `master` branch is 0.1.38. This is causing `update-check` to report an update is available, when there is none.

Potential fixes:
* Update `package.json` to 2.1.38.
* Unpublish NPM package 2.1.38 (probably ideal?)

**Comment by cmmarslender** [comment]
2.1.38 is correct... I pushed to the incorrect remote when i updated that

**Comment by cmmarslender** [comment]
there was confusion about WP Local Docker v2 with a version that was 0.x.x, so updated versions to be more intuitive.
