### ISSUE TITLE
503 Error while using in WSL2 Ubuntu

### ISSUE THREAD

**Issue by provineet** [10up/wp-local-docker-v2#203]
I am using Ubuntu-20.04 on WSL2. I installed 10updocker and created an environment. 

While creating I got an error that 10updocker couldn't modify the /etc/hosts file. Initially I thought it was permissions so I changed them to 777, still no luck with that.

The real issue is when I visit 127.0.0.1:80 I get this error:

**503 Service Temporarily Unavailable
This usually happens if your environment is turned off or hasn't finished starting. Try running 10updocker start <environment>

10up/nginx-proxy**

When I run `docker container ls` command it seems all the containers are running without an issue.

![Screenshot (3)](https://user-images.githubusercontent.com/8990951/116939546-228c0c80-ac8a-11eb-99bf-0a37413bff9b.png)

I can visit phpmyadmin and mailcatcher without an issue.

**Comment by nicholasio** [comment]
You have to modify the windows hosts file yourself, automatically updating hosts file doesn’t work under wsl bc updating /etc/hosts in WSL has no effect on windows.

**Comment by vineet05** [comment]
I have modified the file in windows as well. It is giving me 503 unavailable error. Even in the WSL2 environment it is giving me 503. 

![Screenshot (6)](https://user-images.githubusercontent.com/8990951/116944140-83b7de00-ac92-11eb-95df-0ee635723ae9.png)

**Comment by vineet05** [comment]
issue resolved after I restarted my machine, all working fine. Thanks for help.

**Comment by provineet** [comment]
yeah corrected it ages ago :) Anyways, appreciate that for anyone else who is facing this issue :) Good Work :)
