### ISSUE TITLE
Unable to increasing the file upload size : 413 Error

### ISSUE THREAD

**Issue by provineet** [10up/wp-local-docker-v2#206]
I am using 10updocker v2, I changed PHPFPM Upload Limits and Nginx client_max_body_size values. The Nginx server which is creating the respons is 1.19.10, I can see that inside my WordPress dashboard the limits seem to be increased. 

It is working fine when I upload around 70MB of file, but when I upload a file of size around 150MB it throughs 413 error from a Nginx server 1.13.10. It seems to be Nginx-Proxy container as I checked it is running on 1.13.10. I checked the config file for this server and it says client_max_body_size=100m which I believe is the problem. 

Could you please help how to resolve this?

**Comment by vineet05** [comment]
I am running 10updocker on WSL2 incase that matters.

**Comment by cinghaman** [comment]
Hi @provineet were you able to resolve issue with increasing file size? I am also looking to increase PHPMYAdmin upload size too

**Comment by provineet** [comment]
@cinghaman Yes I was able to resolve. To increase the upload limit you need to do the following:-

- To increase upload limits for the Nginx-Proxy I had to sync the files of the nginx-proxy container's app folder and change "client_max_body_size" values inside nginx.tmpl. Below are my modified files for this:

.wplocaldocker/global
[global.zip](https://github.com/10up/wp-local-docker-v2/files/6555028/global.zip)

- To increase the limit of the serving nginx server & php-fpm service:

1.  Inside your created environment e.g. wp-local-docker-sites/your-site-folder/config/php-fpm . Create a file upload-limits.ini and place the below code in it
`upload_max_filesize = 30000M
post_max_size = 30000M`
2. Edit wp-local-docker-sites/your-site-folder/docker-compose.yml and the below line to the volumes of php-fpm service:
`- './config/php-fpm/upload-limits.ini:/etc/php.d/upload-limits.ini:cached'`
3. Edit wp-local-docker-sites/your-site-folder/config/server.conf and increase the client_body_max_size accordingly.

I increased my upload limit to 30GB which is quite high but its for my development purpose only.

**Comment by cinghaman** [comment]
> @cinghaman Yes I was able to resolve. To increase the upload limit you need to do the following:-
> 
> * To increase upload limits for the Nginx-Proxy I had to sync the files of the nginx-proxy container's app folder and change "client_max_body_size" values inside nginx.tmpl. Below are my modified files for this:
> 
> .wplocaldocker/global
> [global.zip](https://github.com/10up/wp-local-docker-v2/files/6555028/global.zip)
> 
> * To increase the limit of the serving nginx server & php-fpm service:
> 
> 1. Inside your created environment e.g. wp-local-docker-sites/your-site-folder/config/php-fpm . Create a file upload-limits.ini and place the below code in it
>    `upload_max_filesize = 30000M post_max_size = 30000M`
> 2. Edit wp-local-docker-sites/your-site-folder/docker-compose.yml and the below line to the volumes of php-fpm service:
>    `- './config/php-fpm/upload-limits.ini:/etc/php.d/upload-limits.ini:cached'`
> 3. Edit wp-local-docker-sites/your-site-folder/config/server.conf and increase the client_body_max_size accordingly.
> 
> I increased my upload limit to 30GB which is quite high but its for my development purpose only.

Thank you :) for detailed steps.

**Comment by tylercherpak** [comment]
Closing this ticket since it seems we have come to a resolution here. Feel free to reopen if you are still having issues.
