### ISSUE TITLE
Media proxy no longer working with Docker Desktop v3.3.1

### ISSUE THREAD

**Issue by colegeissinger** [10up/wp-local-docker-v2#209]
A few weeks ago I noticed an update to Docker Desktop on my Mac, I updated, and then I immediately noticed my proxied media was returning 404 errors. This is across all sites I have created. For now, I can fix this by removing the original proxy code in the server.conf NGINX rules to something like this [gist](https://gist.github.com/colegeissinger/7cc5760961dfcd520dce5d4d60b0d535)

Anyone else experiencing this?? I also tried to roll back but the problem still exists in the v3.x and trying to go to v2 I can't due to a series of services Docker Desktop updated so I'm kind of stuck with this issue.

I haven't updated to the latest Docker Desktop out of fear of the problem getting worse.

**Steps to Reproduce**

1. Update Docker Desktop 3.3.1.
2. Visit any existing container or create a new one with a media proxy in place.
3. Images should no longer be showing.

**Expected behavior**
I expect all images to be loaded off the proxy.

**Screenshots**

**Environment information**
 - Device: MackBook Pro
 - OS: macOS 10.15.7 (Catalina)
 - Browser and version: Chrome 90.0.4430.212, Firefox 88.0.1 (any browser so far)
 - WordPress version: 5.7.2 (really any WordPress version so far)
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by tylercherpak** [comment]
Hey @colegeissinger looking at the release notes for docker for mac https://docs.docker.com/docker-for-mac/release-notes/ I think there might have been an issues with proxy implementation. Can you try updating to version 3.3.3?

**Comment by colegeissinger** [comment]
Thanks, @tylercherpak ! It seems that updating to 3.3.3 resolved the proxy issue. I'm going to close this ticket!
