### ISSUE TITLE
wp cli command ask to specify environment each time

### ISSUE THREAD

**Issue by oiler** [10up/wp-local-docker-v2#21]
On all environments, every time I run a wp-cli command, I'm asked to complete the specify environment prompt. Seems like something in https://github.com/10up/wp-local-docker-v2/blob/master/src/env-utils.js#L46 is returning false when it shouldn't?

* I've tested in my project root, my project `wordpress` folder, and in my sites root
* I've tried restarting Docker, restarting 10updocker services, and updating to v2.2.0
* My config is using a custom file path for .wplocaldocker so perhaps that is a contributor.
* (edited to add) I just realized i'm using node 11.0.0 although i'm not sure yet if that is a factor

screenshot: 
![screenshot 2019-02-05 13 06 08](https://user-images.githubusercontent.com/665921/52294379-2dd71d00-2947-11e9-8ac5-a8bf067950ca.jpg)

**Comment by Viper007Bond** [comment]
FWIW I have a custom site folder set and it works fine for me with Node v10.x. It even starts up the Docker images first.

**Comment by oiler** [comment]
I figure it's environmental, but so much is off for me i figured it was worth filing in case it's just something that hasn't been tested my with a custom sites folder.

For example, I did some debugging in the source...

In this [line 48](https://github.com/10up/wp-local-docker-v2/blob/master/src/env-utils.js#L48) the result of `sitesPath()` returns a string for me, not an array, so this is where the env check fails:
```node
    if ( cwd.indexOf( await sitesPath() ) === -1 ) {
        return false;
    }
```
And even when I let that string pass through the rest of the function, when it goes through [ln63](https://github.com/10up/wp-local-docker-v2/blob/master/src/env-utils.js#L63) and [ln66](https://github.com/10up/wp-local-docker-v2/blob/master/src/env-utils.js#L66) the returned `cwd` value is "Users", which is pulled from my file path of `/Users/USERNAME/Documents/repo/SLUG`

Anyhow, i'm just hard coded my site slug to return in this function so I can use wp-cli and this isn't an urgent issue for me. I'm new to the tool and I love it and want others to use it, so in case this looks like something that's a real issue, I'm happy to help debug more.

**Comment by cmmarslender** [comment]
Can you try updating to the latest version (just released) and see if it helps the issue? I fixed a few other bugs with environment detection based on the current path and am curious if it will help with your issue as well. 

If the issue still persists, can you let me know if you see a `.config.json` file in the root directory of your environment (would be next to the generated docker-compose.yml and wordpress folders)

If the `.config.json` file exists there, can you let me know the following:

- What is the full path to the environment directory that is not being detected
- What is the value of `sitesPath` as specified in `~/.wplocaldocker/config.json`

**Comment by oiler** [comment]
Updated and it looks like the issue (for me) is still there. 
I do have `config.json` files for each of my environments, yes.
* full path to environment directory = `/Users/USERNAME/Documents/repo/SLUG`
* value of sitesPath in global config = `/UsersUSERNAME/documents/repo`

Here's an annotated version of this segment of env-utils.js, so you can see fully what my environment is printing out:
```node
const parseEnvFromCWD = async function() {
    let cwd = process.cwd();
console.log(cwd); // returns `/Users/USERNAME/Documents/repo/SLUG`

    // if ( cwd.indexOf( await sitesPath() ) === -1 ) {
    //     return false;
    // }
console.log(cwd.indexOf( await sitesPath() )); // returns -1

    // if ( cwd === await sitesPath() ) {
    //     return false;
    // }

 //    // Strip the base sitepath from the path
     cwd = cwd.replace( await sitesPath(), '' ).replace( /^\//i, '' );
console.log(cwd); // returns `Users/USERNAME/Documents/repo/SLUG`

 //    // First segment is now the envSlug, get rid of the rest
    cwd = cwd.split( '/' )[0];
console.log(cwd); // returns `Users`

    // Make sure that a .config.json file exists here
    let configFile = path.join( await sitesPath(), cwd, '.config.json' );
    // if ( ! await fs.exists( configFile ) ) {
    //     return false;
    // }
console.log(configFile); // returns `/Users/USERNAME/documents/repo/Users/.config.json`

    return cwd;
};
```

From what I can tell, two things are happening. 
1) the initial indexof check is not passing and returning false
2) if i skip that indexof logic, the "Strip the base sitepath from the path" isn't parsing the my path properly. so in that step i can hard code my site slug and the rest of the function works as expected

**Comment by cmmarslender** [comment]
One thing I noticed in your two paths above - in one case "Documents" has a capital "D" while in the other case, it is lowercase. Its very possible that is causing the issue. Can you make sure that your config is updated with whichever is correct and let me know if that solves the issue?

**Comment by oiler** [comment]
oh hell I think that's it. I'll take a look at my initial setup to see if I just initially typed the path in wrong or if there was something in the setup that led me astray. either way, thanks to all for looking at this. If you'd like, I'd be happy to PR a commit to add a `toLowerCase` conversion to cwd to avoid the instance of other people being as dumb as me

**Comment by cmmarslender** [comment]
Probably can only do `toLowerCase` in the `parseEnvFromCWD` method - I think if we just make the `cwd` and the `sitesPath` both lowercase and then compare, we could match a situation like this. I'd love a PR for that.

**Comment by cmmarslender** [comment]
Working on some speed improvements and fixed this while I was in there. This should be resolved with the next release.
