### ISSUE TITLE
Import database 

### ISSUE THREAD

**Issue by cinghaman** [10up/wp-local-docker-v2#213]
Trying to import database both through WP CLI command and directly uploading to PHPmyadmin gives issue, on WP CLI command I get this error
Error: Import file missing or not readable: db-import.sql

Doing some research pointed that it could be due to the PHPmyadmin upload size limit to 2048k, couldn't find any way to increase that. 

I looked into docker-compose.yml file and did not see any definition for MySQL or mariaDB or phpmyadmin image being called in.

**Comment by eagl3s1ght** [comment]
I have done it successfully, you are probably just putting the .sql file in the wrong directory. Did you put it in the wordpress folder? If you run wp command from root directory it will look for files in /wordpress

**Comment by cinghaman** [comment]
> I have done it successfully, you are probably just putting the .sql file in the wrong directory. Did you put it in the wordpress folder? If you run wp command from root directory it will look for files in /wordpress

Hi yes finally figured it out from the docs it looked like i should run command from my-site-test but it should be my-site-test/wordpress/
