### ISSUE TITLE
PHPCS / WPCS Issues

### ISSUE THREAD

**Issue by davedoesthings** [10up/wp-local-docker-v2#216]
**Describe your question**

Hello!

I have been trialling WPLD on a couple of projects with a view to moving my team to use this across the board. Generally things have been good, however I've noticed that PHPCS doesn't seem to be working with WPCS when working on a WPLD project.

I'm using the latest release of Visual Studio Code, with globally installed phpcs, and a /wpcs/ folder within the project.

Using Valet, FlyWheel etc, everything works as you would expect; the sniff violations are being returned.

However, with WPLD projects, it appears that phpcs is definitely firing, but nothing is being returned by way of any violations.

I can only assume that something to do with the fact the project lives within a WPLD Docker instance is the issue, but it's not immediately clear what.

Is there secret sauce required by way of docker-compose.yml configuration to make this work, or is just a particular quirk of working within Docker?

Any insight gratefully appreciated! :)

**Comment by provineet** [comment]
With this setup, WPCS is working fine on VSCode, wplocaldocker on all my machines (Ubuntu, Mac, WSL2)

Install these packages via composer in your theme or plugins folder.
```
{
  "require-dev": {
    "wp-coding-standards/wpcs": "^2.2",
    "dealerdirect/phpcodesniffer-composer-installer": "^0.7.1",
    "php-stubs/wordpress-stubs": "^5.4",
     }
}
```
In your vscode->settings.json (local to your project) add these lines:

```
{
  "phpcbf.executablePath": "./vendor/bin/phpcbf",
  "phpcbf.standard": "WordPress",
}
```

Lastly, I am using phpcbf ( persoderlind.vscode-phpcbf ) vscode extension along with PHP IntelliSense and Intelephense. I hope this will work for you.

**Comment by davedoesthings** [comment]
Closing off as I've switched to a composer driven approach as suggested, though it's not quite working 100% as I'd like it, it is at list firing.
