### ISSUE TITLE
Deprecation error when creating new site

### ISSUE THREAD

**Issue by barryceelen** [10up/wp-local-docker-v2#222]
```
Error : time="2021-06-18T00:47:56+02:00" level=warning msg="network wplocaldocker: network.external.name is deprecated in favor of network.name"
time="2021-06-18T00:47:56+02:00" level=warning msg="volume wplocaldockerCache: volume.external.name is deprecated in favor of volume.name"
```

I suppose things should be specified like this:

```
volume:
    external: true
    name: <cool-volume-name>
```

**Environment information**
 - Device: Macbook Air M1
 - OS: Big Sur 11.4
 - Docker Desktop version: 3.4.0 (65384)

**Comment by achyuthajoy** [comment]
Getting the same error on Windows 10. Unable to create sites.

wp-local-docker v2.8.1
docker-desktop v3.5.2

Screenshot
![Screenshot](https://d.pr/i/Lxvid0+)

**Comment by NicestRudeGuy** [comment]
@turtlepod  try to create a fresh site without removing the default contents

**Comment by xavortm** [comment]
Without removing default content, again on M1, Node 12; Docker version 20.10.7, build f0df350;

`time="2021-08-04T23:53:38+03:00" level=warning msg="network wplocaldocker: network.external.name is deprecated in favor of network.name"`

And in the end `no matching manifest for linux/arm64/v8 in the manifest list entries`

**Comment by dustinrue** [comment]
@xavortm image is giving you the no matching manifest error?

**Comment by xavortm** [comment]
Showed up after running `10updocker create` and filling in all questions. Recorded a quick video as well: [dropbox video](https://www.dropbox.com/s/by34yh8yruzyxm0/Screen%20Recording%202021-08-05%20at%200.05.57.mov?dl=0)

If I run the `10updocker create` command with a new site name, the same message outputs. I see it also when running delete as seen above. 

Only information I found was this: [mysql docker issue 318](https://github.com/docker-library/mysql/issues/318) that could be relevant to M1 _"Hoping for ARM support for Apple Silicon M1, etc. in the official Docker images, using mysql/mysql-server for now instead."_

**Comment by dustinrue** [comment]
Ok, looks like it is the global gateway image. You can install our test version using `npm install -g wp-local-docker@release_2_8_2`. Once installed, you need to run `10updocker configure` and select all default options until you are asked `Do you want to reset your global services configuration? This will reset any customizations you have made.` Select 'y' (yes) for this question. This will replace your global configuration with an updated one that spec's some new containers. You may still get the deprecated warning but you should be able to create sites on M1.

**Comment by xavortm** [comment]
That's awesome, solved my issue and I managed to open the site locally 👍  I hope this would also solve @barryceelen 's issue🤞

No warnings shown btw, 

```
✔ Environment directories have been created...
✔ Certificates are generated...
✔ Docker-compose configuration is created...
✔ Configuration files are copied...
✔ Global services are running...
✔ MySQL has started...
✔ Database is created...
✔ docker-test is started...
✔ WordPress is downloaded...
✔ WordPress config is created...
✔ WordPress is installed...
✔ Rewrite rules structure is updated to /%postname%/...
✔ Added domains to the hosts file...

Successfully Created Site!
Homepage: https://docker.test/
WP admin: https://docker.test/wp-admin/
```

**Comment by dustinrue** [comment]
No problem. We'll have more optimized images (particularly the PHP ones since they are currently emulated on M1) before too long. These changes will at least keep you going

**Comment by phpbits** [comment]
I'm getting the same error. The containers were created but the `wordpress` folder is totally empty. Anyone here experienced the same issue? Thanks!

<img width="819" alt="Screen Shot 2021-10-03 at 3 53 06 AM" src="https://user-images.githubusercontent.com/3365507/135730155-81f0a5ba-8ba2-4751-af9b-8549235f93d4.png">

**Comment by tylercherpak** [comment]
Hey y'all 👋 

This issue should be resolved in the latest release.

Let us know if you are still having issues.

Thanks!

**Comment by tcmulder** [comment]
I'm still having this issue. I've done @dustinrue's [recommendation](https://github.com/10up/wp-local-docker-v2/issues/222#issuecomment-892980427) and still see the error:

```
WARN[0000] network wplocaldocker: network.external.name is deprecated in favor of network.name
WARN[0000] volume wplocaldockerCache: volume.external.name is deprecated in favor of volume.name
```

every time wp cli runs any of its commands. This is on v3.0.0 installing a new site with `10updocker create`, no plugins installed using the twentytwentyone theme.

I was getting this before upgrading to 3.0.0. I'm not also getting a 3rd error every time as well:

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'newrelic.so' (tried: /usr/lib/php/20190902/newrelic.so (/usr/lib/php/20190902/newrelic.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/newrelic.so.so (/usr/lib/php/20190902/newrelic.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

Everything appears to work... just annoying having to skip past all these warnings to see if everything succeeded. Note this happens after installation as well, e.g. if I run `wp option get home` the same three warnings appear before my URL gets output to the console.

Environment information

- Device: Macbook Pro M1
- OS: Monterey 12.0.1
- Docker Desktop 4.3.2 (72729)

**Comment by eduardovillao** [comment]
I @tcmulder, had the same problem here and solve it when i remove the Docker Compose config to use v2 (check your Docker Desktop settings).

But i still have the same issue with PHP Warning!
