### ISSUE TITLE
Remove the default content Error while create

### ISSUE THREAD

**Issue by JanKruft** [10up/wp-local-docker-v2#231]
**Describe the bug**

**Steps to Reproduce**

1 . 10updocker create

? What is the primary hostname for your site? (Ex: docker.test) dev.test
? Are there additional domains the site should respond to? No
? What version of PHP would you like to use? 7.4
? Do you want to install WordPress? Yes
? Select a WordPress installation type: Single Site
? Site Name dev.test
? Admin Username admin
? Admin Password password
? Admin Email admin@example.com
? Do you want to remove the default content? Yes
? Do you want to set a proxy for media assets? (i.e. Serving /uploads/ directory assets from a produ
ction site) No
? Do you need Elasticsearch No

2.  While removing default content

✔ Rewrite rules structure is updated to /%postname%/...
 Error : Warning: Widget 'search-2' doesn't exist.
Warning: Widget 'recent-posts-2' doesn't exist.
Warning: Widget 'recent-comments-2' doesn't exist.
Warning: Widget 'archives-2' doesn't exist.
Warning: Widget 'categories-2' doesn't exist.
Warning: Widget 'meta-2' doesn't exist.
Error: No widgets deleted.

3. Project files created . But installation not successful

**Environment information**
 - Device: 
 - OS: 
 - Docker Desktop version: Docker version 20.10.7, build 20.10.7-0ubuntu1~21.04.1 | docker-compose version 1.26.2, 
 - WordPress version:  Latest

I assume the issue is related to a change in latest WordPress version and Widget Blocks 
Quick solution let the installer finish with this error.

**Comment by benlk** [comment]
> Project files created . But installation not successful

When the install process fails at this point, it will fail to create `/etc/hosts` entries.

**Comment by tylercherpak** [comment]
Hey y'all 👋 

This should be fixed in the latest release. 

Let us know if you run into any issues.

Thanks! 😄
