### ISSUE TITLE
Ubuntu on WSL 2 unable to install

### ISSUE THREAD

**Issue by blonestar** [10up/wp-local-docker-v2#233]
Unable to install WP Local Docker v2 on Ubuntu 20.04 LTS (on Windows)

![image](https://user-images.githubusercontent.com/5240133/130283430-b93199bf-6c24-497c-8014-14fe88134f43.png)

Steps to reproduce:
1. clean install Ubuntu 20.04 LTS on Windows 10
2. sudo apt update
3. sudo apt upgrade
4. sudo apt install nodejs npm
5. npm install -g wp-local-docker

**Comment by dustinrue** [comment]
Try using nvm and using an lts release of node. That should resolve the issue you are seeing.

**Comment by blonestar** [comment]
Thanks for quick reply :)
I've reset Ubuntu, and do the apt update and upgrade.
I've manage to install nvm and install latest lts node.
> nvm install --lts
but 10updocker failed to install properly :(

![image](https://user-images.githubusercontent.com/5240133/130289038-5b789a55-fc55-42d3-9118-5b415cc3570f.png)

**Comment by abdullah1908** [comment]
@dustinrue I am facing a few different errors with the same environment.
![screenshot002](https://user-images.githubusercontent.com/14175927/130290644-ffde1d9c-9801-450d-ade1-6cab7d7fca5c.png)
![screenshot001](https://user-images.githubusercontent.com/14175927/130290652-d69e94a7-dcc6-4fc5-aba9-ce5bc520e789.png)

**Comment by tylercherpak** [comment]
Looks like an issue with `nodegit`, can you confirm that `git` is installed correctly.

**Comment by blonestar** [comment]
After restart (Win) 10updocker was there. I think my computer, Windows, is messed up a bit and WSL 2 does not function well with Docker or something. Ubuntu console and Docker for Win has crashed few times.
NVM and Node LTS did help, thank you. :)
