### ISSUE TITLE
10updocker logs needs a default tail value

### ISSUE THREAD

**Issue by moraleida** [10up/wp-local-docker-v2#26]
The first time you use `10updocker logs` in a project it works as a regular `tail` command, which is expected. However, if you close the logs and spend some time working on that project and using the site (i.e: generating logs but not streaming them), the next time you call `10updocker logs` the output will be scrolled starting from the last log you viewed. This can sometimes be weeks worth of log messages and take a very long time to finish. This is because `10upocker logs` is a wrapper around `docker-compose logs`, which has a default value of `--tail="all"`.

The only solution I found was to always run `10updocker logs --tail=100` so regardless of the size of the log file the tail starts somewhere close to the end. Ideally there's should be a default value for `--tail` if not provided by the user. Something like `--tail=200` should be enough for most use-cases.

**Comment by eugene-manuilov** [comment]
This is implemented in #123 and will be shipped with `2.8.0`. The default behavior replicates `docker-compose` approach that uses `all` by default.

```sh-session
10updocker logs --tial=10
```

**Comment by eugene-manuilov** [comment]
It has been implemented and merged via #123. We can consider this ticket as done.
