### ISSUE TITLE
Move files to another machine

### ISSUE THREAD

**Issue by stephanesoares** [10up/wp-local-docker-v2#27]
I would like to know if it is possible to start a project to check if the domain is created in the windows hosts file, and if it is not already being added at that moment?

It would be a good feature for when we migrate the files to another machine that does not contain this project.

It avoided that a create had to be done and then rather to replace the files.

**Comment by cmmarslender** [comment]
The recommended way to move an environment to another machine would be with wpsnapshots (Create the snapshot, and then `10updocker create` on the new machine and then pull the snapshot down).

If you do need to manage hosts though, you can use the helper `10updocker-hosts`. For example:
`sudo 10updocker-hosts add myhost.test`
`sudo 10updocker-hosts remove myhost.test`

**Comment by stephanesoares** [comment]
Its no possible turn '10updocker start' comand verify if url exist in .hosts and if not exists add it ?
