### ISSUE TITLE
10updocker create fails with "cannot start service gateway" or "cannot start service mysql"

### ISSUE THREAD

**Issue by tnorthcutt** [10up/wp-local-docker-v2#28]
I installed with:
`npm install -g wp-local-docker`

Then ran:
`10updocker create`, accepting all defaults.

Full output here, of two different attempts: https://gist.github.com/tnorthcutt/966c594fc0f98733b797bc31e86da754

Seems to fail around the `Starting global_mysql_1` or `Starting global_gateway_1` step.

Happy to provide more info to help debug!

**Comment by cmmarslender** [comment]
based on the error messages, you have something else running in docker that is already binding port 443 and 3306.

If you stop whatever containers are using those ports, you should be good to go with this.

**Comment by tnorthcutt** [comment]
Thanks, @cmmarslender! Looks like that was it.
