### ISSUE TITLE
Cant start the website: The command '/bin/bash -c chown ${CALLING_USER} /var/log/php-fpm' returned a non-zero code: 1

### ISSUE THREAD

**Issue by jramiresbrito** [10up/wp-local-docker-v2#280]
Hey guys I'm trying to setup a website from a wsl2 distro. This is my environment

W11 21H2, build: 22000.376
WSL2 with Ubuntu 20.04.3 LTS
Node v16.13.1
NVM 0.39.1
Yarn 1.22.17
Docker version 20.10.12 build e91ed57 (installed inside the Linux)
Docker compose version 1.29.1 build c34c88b2
**10updocker 3.0.1**

When I try to create a website, this error raises:

```bash
Error : Creating network "myblog-test_default" with the default driver
Building phpfpm
The command '/bin/bash -c chown ${CALLING_USER} /var/log/php-fpm' returned a non-zero code: 1
Service 'phpfpm' failed to build : Build failed
```

Can't figure out how to set these permissions.

**Comment by marlonlamancio** [comment]
Hey guys, hope everything is fine with you.

I'm having same issue here:

`✔ Environment directories have been created...
✔ Certificates are generated...
✔ Docker-compose configuration is created...
✔ Configuration files are copied...
✔ Global services are running...
✔ MariaDB has started...
✔ Database is created...
⠸ Starting docker containers for manjaro-test...
 Error : time="2022-01-17T14:58:38-03:00" level=warning msg="network wplocaldocker: network.external.name is deprecated in favor of network.name"
time="2022-01-17T14:58:38-03:00" level=warning msg="volume wplocaldockerCache: volume.external.name is deprecated in favor of volume.name"
phpfpm Pulling 
phpfpm Error 
1 error occurred:
	* Status: The command '/bin/bash -c chown ${CALLING_USER} /var/log/php-fpm' returned a non-zero code: 1, Code: 1
`

My environment:

Manjaro Linux 21.2.1 Qonos
Node v17.3.1
Npm 0.39.1
Docker version 20.10.12, build e91ed5707e
Docker Compose version 2.2.2
10updocker 3.0.1
I'm using zsh

Any thoughts would be helpful! Thanks!

**Comment by tylercherpak** [comment]
Hey y'all.

I believe we have this fixed in the beta version we are currently testing. You can install that version by running `npm i -g wp-local-docker@next` 

Let me know if that works for your issue. Thanks!

**Comment by marlonlamancio** [comment]
Hi guys, I hope you're doing well.

@tylercherpak this version fixed the problem here! Thank you very much!

**Comment by jramiresbrito** [comment]
> npm i -g wp-local-docker@next

Hey @tylercherpak thank you. It solves the problem. I'm going to close the issue
