### ISSUE TITLE
Trying to Delete Unused Databases

### ISSUE THREAD

**Issue by jg314** [10up/wp-local-docker-v2#290]
**Describe your question**
I accidentally ran `10updocker configure` which caused me to no longer be able to delete old environments I had created before. To get rid of these websites, I deleted the containers in Docker Desktop and deleted the folders within Ubuntu. Unfortunately, I can't figure out how to delete the unused databases. In phpMyAdmin I don't have permissions to delete the databases, and I can't seem to access mysql from the command line.

I'm trying out WP Local Docker for the first time and am not very familiar with Linux. In case it's helpful, I'm using WSL on Windows 10.

Hopefully you all can point me in the right direction. Thanks a ton!

**Comment by tylercherpak** [comment]
Hey @jg314 

You are running `10updocker delete` and its not working on sites created before running configure? Just want to confirm the command you are running.

I would recommend using a tool like [Sequel Pro](https://sequelpro.com/) for db edits (as a work around). You will need to connect to the db as the root user so you have permissions to delete the databases.

**Comment by jg314** [comment]
Thanks for the quick response @tylercherpak.

You're exactly right. I was running `10updocker delete`, but some of the websites were missing. Luckily, after reading your comment I was able to delete the unused databases by logging into phpMyAdmin using these credentials:

Username: `root`
Password: `password`

Thanks for pointing me in the right direction. I really appreciate it.
