### ISSUE TITLE
Access denied for DB root user

### ISSUE THREAD

**Issue by xipasduarte** [10up/wp-local-docker-v2#3]
I'm testing with all the default configurations (single-site, elasticsearch, etc.).

Somehow I can use the credentials `root|password` on the phpMyAdmin interface. My guess is this has something to do with the network that was configured for all global services `wplocaldocker`, because the CLI is running on the host machine, the network is inaccessible to it.

If there's any other information I can provide to help, let me know.
Thanks

```
Creating database
(node:56169) UnhandledPromiseRejectionWarning: Error: Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
```

**Comment by cmmarslender** [comment]
Can you please send over the full log output from `10updocker create` ?

What OS, docker version, docker-compose version, node version?

**Comment by xipasduarte** [comment]
Thanks for the fast reply. Here goes the information:
- macOS High Sierra
- Node: `v8.12.0`
- `Docker version 18.06.1-ce, build e68fc7a`
- `docker-compose version 1.22.0, build f46880f`
- Full log
```
? What is the primary hostname for your site? (Ex: docker.test) wp.test
? Are there additional domains the site should respond to? No
? What version of PHP would you like to use? 7.2
? Do you need Elasticsearch Yes
? Do you want to install WordPress? Yes
? Select a WordPress installation type: Single Site
? Do you want to remove the default content? Yes
? Site Name wp.test
? Admin Username admin
? Admin Password password
? Admin Email admin@example.com
Ensuring global network exists
 - Network exists
Ensuring global cache volume exists
 - Creating Volume
Ensuring global services are running
Creating global_dns_1         ... done
Creating global_mysql_1       ... done
Creating global_gateway_1     ... done
Creating global_mailcatcher_1 ... done
Creating global_phpmyadmin_1  ... done
Waiting for mysql...

Copying required files...
Generating docker-compose.yml file...
done
Creating database
(node:56849) UnhandledPromiseRejectionWarning: Error: Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
    at Query.<anonymous> (/Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/wp-local-docker/src/database.js:21:25)
    at Query.<anonymous> (/Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/wp-local-docker/node_modules/mysql/lib/Connection.js:502:10)
    at Query._callback (/Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/wp-local-docker/node_modules/mysql/lib/Connection.js:468:16)
    at Query.Sequence.end (/Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/wp-local-docker/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/wp-local-docker/node_modules/mysql/lib/protocol/Protocol.js:396:18
    at Array.forEach (<anonymous>)
    at /Users/username/.nvm/versions/node/v8.12.0/lib/node_modules/wp-local-docker/node_modules/mysql/lib/protocol/Protocol.js:395:13
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
(node:56849) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:56849) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by cmmarslender** [comment]
I'm running a nearly identical environment, and am unfortunately not able to replicate the issue. The only thing I can think of is the MySQL container may have run into issues the first time it started up, but I tried to force that scenario, and didn't have any luck.. 

Assuming you haven't been able to get any environments set up (or are ok with losing any MySQL data in the data volume) you can try to delete and recreate that volume, which should set up the root user again. The following steps stop the containers, update WP Local Docker, and then deletes the mysql volume so that it gets recreated.

- `10updocker stop all`
- `npm update -g wp-local-docker`
- `docker volume rm global_mysqlData`
- `10updocker create`

Let me know if you have any luck with this.

**Comment by xipasduarte** [comment]
I did this before, but I tried it again. No luck 😞 

It really is stuck on the MySQL database creation step, trying to find something that can't be reached. Do you, maybe, have some "special" configuration on Docker for Mac?

**Comment by cmmarslender** [comment]
The only configuration changes I've made to docker are around CPU and Memory settings (both of them are increased a bit I believe). CPU is set to 2 and memory to 8GB.

**Comment by xipasduarte** [comment]
No longer have this issue, it must have been corrected either by a new updated or something on my end.

**Comment by gleatherman** [comment]
having the same issue with latest version 

- macOS Mojave 10.14.3
- node v8.15.1
- Docker version 18.09.2, build 6247962
- docker-compose version 1.23.2, build 1110ad01
- WP Local Docker Version 2.4.2

CREATE Log
`Ensuring global network exists
 - Network exists
Ensuring global cache volume exists
 - Creating Volume
Ensuring global services are running
global_mysql_1 is up-to-date
global_mailcatcher_1 is up-to-date
global_gateway_1 is up-to-date
global_dns_1 is up-to-date
global_phpmyadmin_1 is up-to-date
Waiting for mysql...

Copying required files...
Generating docker-compose.yml file...
done
Creating database
(node:10062) UnhandledPromiseRejectionWarning: Error: Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Query.<anonymous> (/Users/gary/.nvm/versions/node/v8.15.1/lib/node_modules/wp-local-docker/src/database.js:21:25)
    at Query.<anonymous> (/Users/gary/.nvm/versions/node/v8.15.1/lib/node_modules/wp-local-docker/node_modules/mysql/lib/Connection.js:502:10)
    at Query._callback (/Users/gary/.nvm/versions/node/v8.15.1/lib/node_modules/wp-local-docker/node_modules/mysql/lib/Connection.js:468:16)
    at Query.Sequence.end (/Users/gary/.nvm/versions/node/v8.15.1/lib/node_modules/wp-local-docker/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /Users/gary/.nvm/versions/node/v8.15.1/lib/node_modules/wp-local-docker/node_modules/mysql/lib/protocol/Protocol.js:396:18
    at Array.forEach (<anonymous>)
    at /Users/gary/.nvm/versions/node/v8.15.1/lib/node_modules/wp-local-docker/node_modules/mysql/lib/protocol/Protocol.js:395:13
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
(node:10062) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10062) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
