### ISSUE TITLE
wp-cli commands with local files as arguments don't seem to work

### ISSUE THREAD

**Issue by mwm-webdesign** [10up/wp-local-docker-v2#31]
For example this

`10updocker wp eval-file test.php`

results in

`Error: 'test.php' does not exist.`

Even though the file is present. Same goes with the absolute path to the file.

And same also for other commands like `10updocker plugin install mylocalplugin.zip`

It seems as if `10updocker wp` is not seeing the files.

**Comment by cmmarslender** [comment]
The wp-cli commands get run inside of the php docker container, so the path won't match your host path. The `wordpress` directory in your project is mounted to `/var/www/html` in the container. If you want to use a relative path, make sure it is relative to the `wordpress` directory.

For instance, if `mylocalplugin.zip` was right inside the `wordpress` directory, you should be able to do `10updocker wp plugin install mylocalplugin.zip`
