### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by justinmaurerdotdev** [10up/wp-local-docker-v2#332]
### Is your enhancement related to a problem? Please describe.

In the [words of stitcher.io](https://stitcher.io/blog/php-version-stats-january-2023):
> PHP 8.0 went into [security fixes only mode](https://www.php.net/supported-versions.php) at the end of last year, and I hope to see its usage decline a lot more this year. Keep in mind that PHP 8.0 will reach end of life on November 26, 2023. So it's crucial that projects start preparing to upgrade in the coming months.
>
> PHP 7.4 reached end of life last year, so at the same time it's worrying that more than 25% of projects are still using it! Let's hope to see this number decline soon.

Our team is really enjoying the `10updocker` workflow. We want to jump from 7.4 to 8.2 (because of the features available in 8.2), but we don't want to have to give up the 10updocker setup! [There's an old, approved PR](https://github.com/10up/wp-local-docker-v2/pull/319) for adding 8.1, but it's never been merged. And now it's old enough that 8.2 should really be the default.

The author of that ticket says
> While it's easy to switch to 8.1. by editing docker-composer.yml and restarting, this PR would make things a little quicker.

I attempted it, and things started breaking. If no 8.1/8.2 support will be added to the 10updocker setup, do you think you could add some documentation for how to upgrade the PHP image?

I guess, in general, it would also be nice to have some clarification about the status of this project. I know it has been a year since any changes were made to the master branch.

Thanks in advance for any kind of official response here. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fanksin** [comment]
I agree. PHP 8+ version support should come into this project. I am digging it. If I can manage it, I will send a PR, and you can merge into your local maybe, if the maintainer doesn't merge it. @justinmaurerdotdev

**Comment by justinmaurerdotdev** [comment]
I decided to try this again, since I noticed that 10up's 8.2 docker image had been updated, and it looks like it...just worked this time. 

I just changed the `image` for the `phpfpm` container to look like this: `image: '10up/wp-php-fpm-dev:8.2-ubuntu'` and it appears to be functioning just fine.
