### ISSUE TITLE
How to clear logs?

### ISSUE THREAD

**Issue by jperks-mower** [10up/wp-local-docker-v2#335]
### Troubleshooting

- [X] I have attempted to troubleshoot this already

### Describe your question

I am having an issue when running 10updocker logs. Logs appear, but at the end I receive the following error message, and no new logs appear: 

error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value

Is there a way to clear the log file to remove the invalid character? Is there another way to resolve the issue?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jperks-mower** [comment]
I was able to fix the issue by deleting the site and recreating it. However, now this is happening on another one of my sites. How can I clear out the log files?

**Comment by jperks-mower** [comment]
Here are some more errors from the logs:

phpfpm-1     | [08-Mar-2023 15:37:02] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value

**Comment by jperks-mower** [comment]
I'm still having this issue. Is there any way to clear the PHP logs?

**Comment by jperks-mower** [comment]
Hello,

Here is the latest:
```
[environment name redacted      | 10.0.0.3 - - [09/Nov/2023:14:33:22 +0000] "POST /wp-admin/admin-ajax.php HTTP/1.1" 200 109 "URL redacted/wp-admin/post-new.php?post_type=acf-field-group" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0"
error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value


 Error : error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value
```

Is there no way to clear the logs? If not, how can I fix this issue?

**Comment by PumpAdmin** [comment]
Here is the latest after running "10updocker logs":

 Error : time="2024-01-25T08:47:51-05:00" level=warning msg="network wplocaldocker: network.external.name is deprecated. Please set network.name with external: true"
time="2024-01-25T08:47:51-05:00" level=warning msg="volume wplocaldockerCache: volume.external.name is deprecated in favor of volume.name"
error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value

**Comment by jperks-mower** [comment]
Here is the latest after running "10updocker logs":

```
error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value


 Error : time="2024-02-12T15:14:22-05:00" level=warning msg="network wplocaldocker: network.external.name is deprecated. Please set network.name with external: true"
time="2024-02-12T15:14:22-05:00" level=warning msg="volume wplocaldockerCache: volume.external.name is deprecated in favor of volume.name"
error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value
```

**Comment by jperks-mower** [comment]
I found out how to clear the logs. Make sure all containers are stopped, then run:

`docker system prune`

**Comment by PumpAdmin** [comment]
[like]  Bruce Wodka reacted to your message:
________________________________
