### ISSUE TITLE
Is it possible to run commands non-interactively 

### ISSUE THREAD

**Issue by elindydotcom** [10up/wp-local-docker-v2#349]
### Troubleshooting

- [X] I have attempted to troubleshoot this already

### Describe your question

I was wondering if it's possible to run commands such as 10updocker create and pass parameters on the command line (or via environment vars) instead of responding to interactive prompts?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dustinrue** [comment]
It is currently not possible to create sites in a single command. I recommend creating a project template you can use to generate additional environments from. As long as what you generate is placed into your configured wp-local-docker sites directory it will work as expected.
