### ISSUE TITLE
Import of DB with PHPMyAdmin not working

### ISSUE THREAD

**Issue by mbootsman** [10up/wp-local-docker-v2#40]
I opened PHPMyAdmin on localhost:8092.
Opened a DB of an environment
Removed all tables.
Tried to import a DB and PHPMyAdmin gives me only this: `Incorrect format parameter`
I have tried multiple DB backups (sql files), and also compressed (zip files).

[update] It's probably because of upload limits, so I've edited the php.ini file in /usr/local/php with this:
```
upload_max_filesize = 1000M
post_max_size = 1000M
```

I see these values in a phpinfo page I created, but PHPMyAdmin still uses 2M as max upload size.

**Comment by jeffpaul** [comment]
Thanks for the question and feedback @mbootsman, we've got some folks out right now but will get back to you on this once we're back to full capacity.  In the meantime, if you see any additionally related error messaging that can help us triage this please let us know... thanks!

Related thread from Twitter: https://twitter.com/mbootsman/status/1171127027543478273

**Comment by williamdes** [comment]
Hello @mbootsman maybe you should open an issue at https://github.com/phpmyadmin/phpmyadmin/issues :)
Or use the latest version available

_I found this issue on my Google Alerts_

**Comment by mbootsman** [comment]
I'm using the included phpmyadmin, is there a way to update it?

 > Hello @mbootsman maybe you should open an issue at https://github.com/phpmyadmin/phpmyadmin/issues :)
> Or use the latest version available
> 
> _I found this issue on my Google Alerts_

**Comment by mbootsman** [comment]
Thanks I have added some extra info in the opening post.

> Thanks for the question and feedback @mbootsman, we've got some folks out right now but will get back to you on this once we're back to full capacity. In the meantime, if you see any additionally related error messaging that can help us triage this please let us know... thanks!
> 
> Related thread from Twitter: https://twitter.com/mbootsman/status/1171127027543478273

**Comment by williamdes** [comment]
> I see these values in a phpinfo page I created, but PHPMyAdmin still uses 2M as max upload size.

Are you using Nginx or Apache ?

Please have a look to https://github.com/phpmyadmin/phpmyadmin/issues/14397 and https://github.com/phpmyadmin/phpmyadmin/issues/14535

Be sure your web server is not limiting the max file size

See http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

Try to use the https://docs.phpmyadmin.net/en/latest/config.html#cfg_UploadDir setting to upload large files

**Comment by mbootsman** [comment]
Using nginx, and furthermore it's all just default stuff coming out of the 10updocker configs.

**Comment by mbootsman** [comment]
Also, I tried using wpcli to import the db.
In the environment directory, `dev-test`, a db dump is available `dev-test.sql`. When I use `10updocker wp db import dev-test.sql` I get a message: Error: Import file missing or not readable: dev-test.sql
When I try `10updocker wp db import ~/docker/wp-local-docker-sites/dev-test️/dev-test.sql`, I get the same message. It should be this hard to import a db should it? Really curious if I'm doing something wrong here.

**Comment by williamdes** [comment]
@mbootsman I will try to help you, but this is out of the scope of phpMyAdmin since phpMyAdmin only is a web UI to access databases :)

**Comment by mbootsman** [comment]
I understand, that's why this issue is in the wp-local-docker-v2 repo ;)

> @mbootsman I will try to help you, but this is out of the scope of phpMyAdmin since phpMyAdmin only is a web UI to access databases :)

**Comment by williamdes** [comment]
I found correctly configured files for the v1

 - https://github.com/10up/wp-local-docker/blob/7ec99c7828b5758a68adf8f7f32170e7f9ef4542/config/nginx/default.conf#L48

- https://github.com/10up/wp-local-docker/blob/master/config/php-fpm/php.ini

I followed the trail from your docker-compose in this repo

- https://hub.docker.com/r/10up/nginx-proxy/dockerfile
- https://hub.docker.com/r/jwilder/nginx-proxy/dockerfile
- https://github.com/nginxinc/docker-nginx/blob/e3bbc1131a683dabf868268e62b9d3fbd250191b/mainline/buster/Dockerfile

- https://github.com/jwilder/nginx-proxy/issues/690

@mbootsman You should maybe fix the nginx proxy using https://github.com/jwilder/nginx-proxy#proxy-wide since `10up/nginx-proxy` uses as base `jwilder/nginx-proxy`

I do not know enougth about your docker config at 10up to help you with your cli `10updocker wp db import`

maybe try to follow https://stackoverflow.com/a/49680802/5155484 in order to import the .sql file in the database server directly, I think it is the easiest way to import the file

**Comment by mbootsman** [comment]
Thanks @williamdes, I really think the people of this repo should look into this, and at least see if my problem can be reproduced.

**Comment by Undizzy** [comment]
Hi @mbootsman. I have the same problem.
I found a temporary solution for myself:
in `/global/docker-compose.yml` in the `mysql service`, I added my `volume` and mounted it on the `/ home` folder.
`- "./mysqlData/:/home/mysqlData"`
Put there the database that you need to import.
Using `docker`, I connected to the `global_mysql_1 container` 
`$ docker exec -it global_mysql_1 bash`
and imported the database using the mysql CLI.
`$ mysql -u root -p` _password is: password_
`mysql> use dev-test`
`mysql> source /home/mysqlData/dev-test.sql`

I apologize for the English, used Google Translator)))

**Comment by mbootsman** [comment]
Thanks @Undizzy!
I'm not really sure how you mapped your local path /home/mysqlData to the volume, can you please explain? I feel this will work, just need some more knowledge of where to put my backups so I can import them.

> Hi @mbootsman. I have the same problem.
> I found a temporary solution for myself:
> in `/global/docker-compose.yml` in the `mysql service`, I added my `volume` and mounted it on the `/ home` folder.
> `- "./mysqlData/:/home/mysqlData"`
> Put there the database that you need to import.
> Using `docker`, I connected to the `global_mysql_1 container`
> `$ docker exec -it global_mysql_1 bash`
> and imported the database using the mysql CLI.
> `$ mysql -u root -p` _password is: password_
> `mysql> use dev-test`
> `mysql> source /home/mysqlData/dev-test.sql`
> 
> I apologize for the English, used Google Translator)))

**Comment by Undizzy** [comment]
to @mbootsman .
I us Windows 10 & docker.
in `C:\Users\[username]\AppData\Roaming\npm\node_modules\wp-local-docker\global` i created a folder `mysqlData` and edited the file `docker-compose.yml` (it is my file https://github.com/Undizzy/docker-compose.yml). In folder `mysqlData` i put my backups.
 I unfortunately do not know where this file is located on Linux or Mac ((((

**Comment by mbootsman** [comment]
Thanks, that totally works. Path on Ubuntu is `/home/linuxbrew/.linuxbrew/lib/node_modules/wp-local-docker/global/`

I do think this is not a nice/easy way to provide DB imports.

**Comment by esa1975** [comment]
I found a workaround for the size limit. This approach isn't permanent but it at least lets you raise the limit for the current session to import the database via phpmyadmin.

Use `docker ps` to find the CONTAINER_ID for phpmyadmin.

Run `docker exec -it [CONTAINER_ID] bash`, replacing [CONTAINER_ID] with the correct value.

From within the container, copy `/usr/local/etc/php/php.ini-production` to `php.ini` in the same directory.

Use apt to install an editor (i.e. vim or nano) `apt update && apt install vim`.

Edit the new php.ini file to increase `post_max_size` and `upload_max_filesize` to the desired limits. 

Run `apache2ctl restart` so the new php settings can take effect. This will exit the container.

Load localhost:8092 for phpmyadmin and the import limit should now be whatever you set it to.

There's probably a better or more permanent way to apply this workaround but hey, whatever works.

**Comment by dustinrue** [comment]
@mbootsman I looked into this a bit. wp-local-docker-v2 utilizes the phpmyadmin/phpmyadmin image. Turns out the latest image of phpmyadmin/phpmyadmin does NOT configure the max upload size in php at all where, at least some, previous images did.

Here is the new image
```
[dustin@Dustins-Mac-mini ~]$ docker run --rm -ti 8ad87a8e95c4 bash
root@004f0b216f6c:/var/www/html# cat /usr/local/etc/php/conf.d/phpmyadmin-misc.ini
allow_url_fopen = Off
max_execution_time = 600
memory_limit = 512M
```

Here is the old image

```
[dustin@Dustins-Mac-mini ~]$ docker run --rm -ti 626319eaebed bash
root@a496503af277:/var/www/html# cat /usr/local/etc/php/conf.d/php-phpmyadmin.ini
[PHP]
allow_url_fopen = Off
max_execution_time = 600
memory_limit = 512M
open_basedir = /var/www/html:/tmp/:/etc/phpmyadmin/
post_max_size = 512M
upload_max_filesize = 512M

[Session]
session.cookie_httponly = 1
session.hash_function = 1
session.save_path = "/sessions"
session.use_strict_mode = 1

[opcache]
opcache.fast_shutdown = 1
opcache.restrict_api = /disabled/
opcache.save_comments = 0
opcache.use_cwd = 0
opcache.validate_timestamps = 0
```

For this an issue would need to be raised at https://github.com/phpmyadmin/docker/issues.

However, you have other options. wp-local-docker-v2 does expose mysql on port 3306 so you can use any database management app you might have on your system already. Simply connect to 127.0.0.1 port 3306 and log in as root/password. Your other option to import the database is to put the sql file into the doc root of your project (so wp-local-docker-sites/<project>/wordpress) and use `10updocker wp db import <filename>`. This will import the database using wp cli instead of other methods. 

Hope that helps

**Comment by allysonsouza** [comment]
I'm having the same problem, what about the wp cli error while trying to import a database?
`Error: Import file missing or not readable: dev.sql`

It's somewhat related to the max_upload_size or it's a different problem?

**Comment by williamdes** [comment]
By the way: I added `UPLOAD_LIMIT` ENV to the docker image.

@mbootsman I think this issue can be closed

https://github.com/phpmyadmin/docker/pull/261

**Comment by niphoenixo** [comment]
Hi,

I solved import of DB error, by changing UPLOAD_LIMIT=1G at docker-compose.yml

=========================================
myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8083:80"
        environment:
            - **UPLOAD_LIMIT=1G**
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
=============================

**Comment by eugene-manuilov** [comment]
Cool. Thanks for letting us know. I am closing this issue for now. Feel free to open a new one if help is still needed.

**Comment by phpbits** [comment]
`10updocker wp db import mysql.sql` should work as long as `mysql.sql` is inside the `wordpress` folder. Thanks!

**Comment by Dsantacruz** [comment]
> Hi,
> 
> I solved import of DB error, by changing UPLOAD_LIMIT=1G at docker-compose.yml
> 
> myadmin:
> image: phpmyadmin/phpmyadmin
> container_name: phpmyadmin
> ports:
> - "8083:80"
> environment:
> - **UPLOAD_LIMIT=1G**
> - PMA_ARBITRARY=1
> - PMA_HOST=${MYSQL_HOST}
> restart: always
> depends_on:
> - mysqldb



> Hi,
> 
> I solved import of DB error, by changing UPLOAD_LIMIT=1G at docker-compose.yml
> 
> myadmin:
> image: phpmyadmin/phpmyadmin
> container_name: phpmyadmin
> ports:
> - "8083:80"
> environment:
> - **UPLOAD_LIMIT=1G**
> - PMA_ARBITRARY=1
> - PMA_HOST=${MYSQL_HOST}
> restart: always
> depends_on:
> - mysqldb

This worked for me, i agree UPLOAD_LIMIT=1GB

**Comment by cinghaman** [comment]
> Hi,
> 
> I solved import of DB error, by changing UPLOAD_LIMIT=1G at docker-compose.yml
> 
> myadmin:
> image: phpmyadmin/phpmyadmin
> container_name: phpmyadmin
> ports:
> - "8083:80"
> environment:
> - **UPLOAD_LIMIT=1G**
> - PMA_ARBITRARY=1
> - PMA_HOST=${MYSQL_HOST}
> restart: always
> depends_on:
> - mysqldb

Hi Can you please share your full yml file I am getting mysqldb error
