### ISSUE TITLE
Failed to amend DNS records to hosts

### ISSUE THREAD

**Issue by thiras** [10up/wp-local-docker-v2#42]
**Describe the bug**
It fails to add DNS records to the /etc/hosts file, even the password prompt filled correctly.

**Steps to Reproduce**
1. `10updocker create`
2. Create a single site WordPress with default settings
3. Enter the sudo password when prompt appeared

Here is the error;
```
Adding entry to hosts file
Warning: Something went wrong adding host file entries. You may need to add the /etc/hosts entries manually.
```

**Expected behavior**
Add relevant DNS records to hosts file. It's also better to throw out required configuration for creating convenient manual configuration experience.

**Environment information**
 - OS: Ubuntu 18.04
 - Node: v10.13.0
 - Docker: version 18.09.7, build 2d0083d
 - docker-compose: version 1.17.1

**Comment by thiras** [comment]
I've found the problem. My node is installed by nvm which prevents to use any node related commands with sudo. Here is the reference issue; https://github.com/nvm-sh/nvm/issues/43

**Comment by darrylmorley** [comment]
Hi,
I have the same issue, although changing my node installation hasn't helped. I am getting a 503 error when accessing 127.0.0.1 & https://127.0.0.1, I'm not sure what I should be adding to my /etc/host file to fix this or where I can access the WordPress installation?
