### ISSUE TITLE
Allow user to enable/disable xdebug as required

### ISSUE THREAD

**Issue by dustinrue** [10up/wp-local-docker-v2#47]
**Is your enhancement related to a problem? Please describe.**
Despite changes to how file paths are cached in macOS (and possibly Windows) interacting with the site can still be very slow. This seems to be caused by xdebug being enabled at all times. By swapping out the 10up/php-fpm container for one that does not have xdebug installed things become very quick. 

**Describe the solution you'd like**
I propose allowing the user to enable or disable xdebug at environment start time through a flag or config setting for that environment

**Additional context**
This is something I may be able to provide a PR for

**Comment by dustinrue** [comment]
I've realized this is already possible by editing a config file, closing this

**Comment by bitfactory-lasse-vandenboschchristensen** [comment]
Hi dustinrue,

Which file did you edit? 

Cheers,
Lasse

**Comment by bitfactory-lasse-vandenboschchristensen** [comment]
I can confirm that disabling xdebug makes for a much faster (x3) setup. 

For those interested

1) run ```$ 10updocker config```
2) in the environment directory (```/Users/youruser/wp-local-docker-sites```) find ```config/php-fpm/docker-php-ext-xdebug.ini```
3) set the content to:
```
zend_extension=/usr/local/lib/php/extensions/xdebug.so
xdebug.remote_enable = 0
xdebug.remote_autostart = 0
xdebug.remote_host = host.docker.internal
```
or simply set the xdebug.remote_enable and xdebug.remote_autostart variables to 0

Cheers

**Comment by darrylmorley** [comment]
> I can confirm that disabling xdebug makes for a much faster (x3) setup.
> 
> For those interested
> 
> 1. run `$ 10updocker config`
> 2. in the environment directory (`/Users/youruser/wp-local-docker-sites`) find `config/php-fpm/docker-php-ext-xdebug.ini`
> 3. set the content to:
> 
> ```
> zend_extension=/usr/local/lib/php/extensions/xdebug.so
> xdebug.remote_enable = 0
> xdebug.remote_autostart = 0
> xdebug.remote_host = host.docker.internal
> ```
> 
> or simply set the xdebug.remote_enable and xdebug.remote_autostart variables to 0
> 
> Cheers

I would expect this to work without running '10updocker config', i.e. make the amendments and restart? Or is it necessary to run '10updocker config' for this to work? And if you do have to run '10updocker config', does that mean that essentially you have to start from scratch?

**Comment by bitfactory-lasse-vandenboschchristensen** [comment]
@darrylmorley i had to run ```10updocker config``` to be able to find the config directories. But if you are able to do this without you should give it a go. 
Furthermore running ```10updocker config``` won't mean starting from scratch, but just that (according to me) you define a location for the system to dump docker-related configs, setup files, and wp-directories for each 10updocker project. Your existing projects won't be scrapped.
