### ISSUE TITLE
Where is the docker-compose file?

### ISSUE THREAD

**Issue by geeksupport1** [10up/wp-local-docker-v2#50]
Hi,
Thanks for creating and sharing this.

I get https://github.com/10up/wp-local-docker

I can git clone and docker-compose up.

However, V2 does not have a docker-compose.yml.

I am using Windows 10 WSL, npm is not working.

How do I install this using git?

Thanks in advance.

**Comment by christianc1** [comment]
Hi @geeksupport1, this tool relies heavily on node.  You could probably clone this repository on you machine, manually create symlinks to `index.js`, and `hosts.js`, and add them to your PATH.  However, you'll be better served by fixing the underlying issue with npm.

**Comment by tylercherpak** [comment]
Hey @geeksupport1 

To install global npm packages from source you need to clone the repo, run `npm install` and the `npm link`. This will create a symlink in the global folder. More info [here](https://docs.npmjs.com/cli/v6/commands/npm-link). Let us know if you have any other questions. Thanks!
