### ISSUE TITLE
Error thrown while creating database through 10updocker create

### ISSUE THREAD

**Issue by Pehotin** [10up/wp-local-docker-v2#51]
Hey guys. Any idea why I got this error?

**Describe the bug**

(node:69958) UnhandledPromiseRejectionWarning: Error: Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Query.<anonymous> (/usr/local/lib/node_modules/wp-local-docker/src/database.js:37:25)
    at Query.<anonymous> (/usr/local/lib/node_modules/wp-local-docker/node_modules/mysql/lib/Connection.js:525:10)
    at Query._callback (/usr/local/lib/node_modules/wp-local-docker/node_modules/mysql/lib/Connection.js:491:16)
    at Query.Sequence.end (/usr/local/lib/node_modules/wp-local-docker/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /usr/local/lib/node_modules/wp-local-docker/node_modules/mysql/lib/protocol/Protocol.js:404:18
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/wp-local-docker/node_modules/mysql/lib/protocol/Protocol.js:403:13
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:69958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:69958) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Steps to Reproduce**
 10updocker create

**Screenshots**
https://jmp.sh/IrHjbUj
https://jmp.sh/wuRKPe3

**Environment information**
 - OS: MacOS 10.15
 - Node: v10.13.0 (nvm)
 - Docker: v19.03.4
 - docker-compose: v1.24.1, build 4667896

**Comment by tylercherpak** [comment]
Hey @Pehotin 

Sorry for the long delay in reply on this one. Please try the [troubleshooting steps](https://github.com/10up/wp-local-docker-v2/#i-am-having-issues-with-wp-local-docker-what-are-the-best-troubleshooting-techniques) in the readme. And that should resolve the issue for you.

Let us know if you have questions or still having issues.
