### ISSUE TITLE
Add alias for wp --allow-root

### ISSUE THREAD

**Issue by thiras** [10up/wp-local-docker-v2#52]
**Is your enhancement related to a problem? Please describe.**
With current configuration, each wpcli command should have `--allow-root` flag to be able to run since docker user is root by default.

**Describe the solution you'd like**
As the wp-cli's [this issue](https://github.com/wp-cli/wp-cli/issues/1838#issuecomment-219641029) suggests, adding simple `alias wp="wp --allow-root"` line to the `.bashrc` solves the problem. Since this tool intended to be development tool, I see no risk to add this line while creating the containers.

**Comment by dustinrue** [comment]
In a future release the container will no longer run as root and the flag won't be necessary.

**Comment by tylercherpak** [comment]
@dustinrue is this issue resolved now?

**Comment by tylercherpak** [comment]
This is resolved now, let us know if you still have any issues! 😄
