### ISSUE TITLE
Add wp-cli auto-completion 

### ISSUE THREAD

**Issue by thiras** [10up/wp-local-docker-v2#53]
**Is your enhancement related to a problem? Please describe.**
Current setup doesn't support wp-cli auto-completion by default.

**Describe the solution you'd like**
Add auto-completion to the containers as the [official documentation](https://wp-cli.org/#installing) suggest. (See auto-completion section under Install)

**Comment by christianc1** [comment]
Thanks for the suggestion @thiras , we'll look into what it would take to add this in a future version.
