### ISSUE TITLE
phpmemcachedadmin image has been removed from upstream

### ISSUE THREAD

**Issue by dustinrue** [10up/wp-local-docker-v2#61]
**Describe the bug**
hitwe/phpmemcachedadmin:latest no longer exists. The author is now using versioned tags instead

**Steps to Reproduce**

1. Don't have hitwe/phpmemcachedadmin:latest cached locally
2. Try to create a site or pull an updated image
3. See it fail

I will provide a PR to fix this as soon as I can

**Comment by christianc1** [comment]
Related #100 

Fixed in [2.7.0](https://github.com/10up/wp-local-docker-v2/releases/tag/2.7.0)
