### ISSUE TITLE
"ERROR: Setting environment for exec is not supported in API < 1.25 (1.22)" when running PHPUnit via PHPStorm with ENV variables

### ISSUE THREAD

**Issue by aaemnnosttv** [10up/wp-local-docker-v2#75]
**Describe the bug**
As of v2.6.2, when invoking PHPUnit via PHPStorm (configured to connect to local Docker) it show's this error:

> ERROR: Setting environment for exec is not supported in API < 1.25 (1.22)

CLI Interpreter config

![image](https://user-images.githubusercontent.com/1621608/71250972-b70dfd00-2329-11ea-9248-fb7c71ff6580.png)

This appears to be a limitation of the Docker compose file version when running `docker-compose exec` with ENV variables https://github.com/docker/compose/issues/6000

![image](https://user-images.githubusercontent.com/1621608/71251341-c04b9980-232a-11ea-9379-daf752f69b57.png)

Changing the file version to `2.2` as mentioned in the above issue fixes the problem for me.

```diff
- version: '2'
+ version: '2.2'
```

**Expected behavior**

**Environment information**
 - Device: MacBook Pro
 - OS: MacOS 10.14.6
![image](https://user-images.githubusercontent.com/1621608/71251252-7cf12b00-232a-11ea-8348-5fc717185634.png)

**Additional context**

**Comment by dustinrue** [comment]
Thank you for the report! I'll see about adjusting that value.
