### ISSUE TITLE
Upgrade doubles up '~/.ssh:/home/www-data/.ssh:cached'

### ISSUE THREAD

**Issue by dustinrue** [10up/wp-local-docker-v2#76]
**Describe the bug**
After performing an upgrade you may end up with doubled up entries for:

`'~/.ssh:/home/www-data/.ssh:cached'`

**Steps to Reproduce**
1. Upgrade to 2.6.2
2. Perform upgrade of existing environment

**Expected behavior**
A cleaner config

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - Plugins and version: 
 - Theme and version: 
 - Other installed plugin(s) and version(s):

**Additional context**

**Comment by eugene-manuilov** [comment]
@dustinrue can you still reproduce it? I have created an environment using `wp-local-docker@2.5.0` and upgraded it with `wp-local-docker@2.7.0`, but I don't see duplicated volumes.

**Comment by eugene-manuilov** [comment]
Ok, this issue is solved in #143. We can close this ticket.
