### ISSUE TITLE
Upgrade doesn't fully configure php-fpm

### ISSUE THREAD

**Issue by dustinrue** [10up/wp-local-docker-v2#77]
**Describe the bug**
Because of the new containers the php-fpm config needs to be adjusted so that it is pointing at the new location for xdebug

**Steps to Reproduce**

1. Upgrade to 2.6.2
2. Perform upgrade
3. be sad :(

**Expected behavior**

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - Plugins and version: 
 - Theme and version: 
 - Other installed plugin(s) and version(s):

**Additional context**

**Comment by cdwieber** [comment]
As a workaround, I was able to edit `/etc/php.d/docker-php-ext-xdebug.ini` and change the `zend_extension` directive to `/usr/lib64/php/modules/xdebug.so`. Restarting the environment then results in successful XDebug connections.

**Comment by eugene-manuilov** [comment]
@dustinrue is it still an issue? I have tested it with 2.8.0-rc.12 and it seems to work just fine if `ENABLE_XDEBUG` is set to `'true'` (by default it is set to `'false'` which is weird) in the docker-compose.yml file.

**Comment by eugene-manuilov** [comment]
I have updated `ENABLE_XDEBUG` env variable to be `'true'` by default in the new version.

**Comment by nicholasio** [comment]
> I have updated `ENABLE_XDEBUG` env variable to be `'true'` by default in the new version.

I believe one of the reasons this was set to false by default was to improve performance and make xdebug opt-in. However, I'm not sure if we're still seeing a significant performance boost with xdebug disabled. https://github.com/10up/wp-local-docker-v2/issues/47 https://github.com/10up/wp-local-docker-v2/pull/65

**Comment by eugene-manuilov** [comment]
Thanks for the context, @nicholasio, it is very helpful. In this case, I think we can update `remote_enable` and `remote_autostart` to be `0` by default, which should also help if there are performance issues.

**Comment by eugene-manuilov** [comment]
Closing this ticket. Changes made for this ticket has been included in the 2.8.0 release.
