### ISSUE TITLE
Instructions for setting up Memcached

### ISSUE THREAD

**Issue by tlovett1** [10up/wp-local-docker-v2#8]
We should provide instructions for connecting WP with Memcached. It isn't super clear.

**Comment by joseffb-mla** [comment]
Do we have instructions? 

https://redislabs.com/lp/wordpress-memcached/

Doesn't seem to work for me. Is the host name memcached (the container name) or the local uri? Thanks

also how do you tell if it's working? I'm look at the admin with has some request but nothing seems cached. Thanks!

**Comment by PypWalters** [comment]
Here is some unofficial documentation on how to get this up and running:

Put `object-cache.php` from the following plugin in your wp-content folder: https://wordpress.org/plugins/memcached/

Add this to your wp-config: 
```
global $memcached_servers;
$memcached_servers = array('default' => array(
  'memcached',
  '11211',
));
```

If you see an error 'Fatal error: Uncaught Error: Class 'Memcache' not found' 
upgrade your container using `10updocker upgrade` in that environment.

**Comment by joseffb-mla** [comment]
Yes, I found this out but forgot to update this ticket for others. 

You can also use other memcached plugins as well. You just need to use 'memcached' as host instead of localhost.

@PypWalters thanks for getting my attention on this topic to update :)

**Comment by tylercherpak** [comment]
hey everyone, this seems to be resolved so I am going to close this issue. if you are still having issues feel free to repoen. 😄 thanks!
