### ISSUE TITLE
Can't start containers after 2.6.2 update - reports wrong Compose file version

### ISSUE THREAD

**Issue by moraleida** [10up/wp-local-docker-v2#80]
**Describe the bug**

- Tested on Linux Mint 19.3 
- Clean install of 2.6.2, using node/npm 12.13.1 installed via nvm.
- Try to run any command in 10updocker: 

> ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.

- No containers are created, the process halts.
- If instead of running `10updocker start` I run `docker-composer up` all containers are started without errors, but the database is unreachable.
- Changing the version in the project's `docker-compose.yml` does nothing.

Complete output below, trying to start an existing project
```
$ 10updocker start
WARNING: No swap limit support
Locating project files for projectname-local
Ensuring global network exists
 - Network exists
Ensuring global cache volume exists
 - Creating Volume
Ensuring global services are running
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
(node:5738) UnhandledPromiseRejectionWarning: Error: Command failed: docker-compose up -d
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at startGateway (/home/ricardo/.nvm/versions/node/v12.13.1/lib/node_modules/wp-local-docker/src/gateway.js:114:5)
    at Object.startGlobal (/home/ricardo/.nvm/versions/node/v12.13.1/lib/node_modules/wp-local-docker/src/gateway.js:138:11)
    at async start (/home/ricardo/.nvm/versions/node/v12.13.1/lib/node_modules/wp-local-docker/src/environment.js:52:5)
(node:5738) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5738) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to Reproduce**

**Expected behavior**

Commands run and containers are initialized without errors

**Screenshots**

**Environment information**
 - Device: Dell XPS
 - OS: Linux Mint 19.3

**Additional context**

**Comment by dustinrue** [comment]
docker-compose 1.25.0+ is required, recommend updating the docs to reflect this requirement

**Comment by tylercherpak** [comment]
@moraleida were you able to resolve your issue with Dustin's suggestion?

**Comment by moraleida** [comment]
@tylercherpak yes, upgrading docker-compose solved it. We can close this out. Thanks!

**Comment by tylercherpak** [comment]
awesome thanks! just wanted to make sure. Let's leave this open so we update the docs.

**Comment by eugene-manuilov** [comment]
@tylercherpak have you already updated the docs or still need to do it?

**Comment by eugene-manuilov** [comment]
Closing this ticket.
