### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by benlumia007** [10up/wp-local-docker-v2#81]
wp-local-docker-v2, when you guys say it supports, macOS, Windows, and Linux, is this referring to Docker Desktop for Mac and Windows or Docker Toolbox.

**Comment by dustinrue** [comment]
Docker Desktop

**Comment by benlumia007** [comment]
Thanks

**Comment by jeffpaul** [comment]
Re-opening this to note a docs update to more clearly call out Docker Desktop.  @benlumia007 if you're able to help with a PR to adjust the docs accordingly that would be awesome!

**Comment by benlumia007** [comment]
@jeffpaul 
Hello, I haven't done a PR for 10up before, as for the documentation for the version being used ( Docker Desktop for Mac/Windows ), where do I do the PR too.

**Comment by jeffpaul** [comment]
@benlumia007 a PR for the docs located at https://10up.github.io/wp-local-docker-docs/ would be the linked GitHub repo of https://github.com/10up/WP-Local-Docker-Docs/.

**Comment by benlumia007** [comment]
@jeffpaul 
sounds good. I was looking at the includes folder and the installation.md. assuming that this is where it needs to change for Mac and Windows, something from

```
Docker is available for download from the Docker website and will install docker-compose automatically.
```
to 
```
Docker Desktop is available for download from the Docker website and will install docker-compose automatically.
```

**Comment by jeffpaul** [comment]
@benlumia007 sounds good, though adding a link around "Docker Desktop" will also aid others if you don't mind adding that as well?

**Comment by benlumia007** [comment]
@jeffpaul 
sounds good, I'll do that soon
