### ISSUE TITLE
wpsnapshots delete repository

### ISSUE THREAD

**Issue by samimakela** [10up/wp-local-docker-v2#85]
The first attempt to create a repository failed. The second attempt was successful, but now the default repository is the first one (with a different name). 

Is there a way to delete the repository to avoid the need to use the --repository option when pushing.

**Comment by christianc1** [comment]
The WP Snapshots configuration file should be in the user home directory in `.wpsnapshots/config.json`.  You should be able to directly edit repository configurations there.

**Comment by tylercherpak** [comment]
Hey @samimakela You should be able to run `10updocker wpsnapshots configure` and overwrite the exist repository name. Let us know if you have any more questions.
