### ISSUE TITLE
Adjust php.ini settings for WP template

### ISSUE THREAD

**Issue by SmallSansSerif** [10up/wp-local-docker-v2#95]
My WP install and site template that's within my container needs some php.ini changes. How and when in the process can I edit the php.ini? On v2.6.2.

**Comment by SmallSansSerif** [comment]
See this referenced now in https://github.com/10up/wp-local-docker-v2/issues/86

Did see other options take but with that method but still can't get post_max_size to update past 150.

**Comment by dustinrue** [comment]
@SmallSansSerif ,

Make sure you do a `10updocker stop; 10updocker start` to rebuild the container to be completely sure it is loading the new value. However, the nginx config would also need to be adjusted.

**Comment by SmallSansSerif** [comment]
Yeah, still didn't work. Template still thinks it's set to 150. I had edited the client_max_body_size in default, develop files in nginx config folder too to match other settings.

**Comment by frankypixels** [comment]
ADD THE EXACT WAY TO DO THIS TO THE DOCUMENTATION.

It's a valid need. Some projects require larger file sizes/upload times. Denote it in documentation.

I have no idea how to fix this.

**Comment by tylercherpak** [comment]
This issue should be resolved in the RC version that was just released. `npm i -g wp-local-docker@next` to install the RC version, then you can run 10updocker upgrade on the environment and this will mount the `docker-php-ext-xdebug.ini` file in the correct directory and it should pick up your changes. (remember to restart env when you edit the ini file) Let me know if you have any questions.
