### ISSUE TITLE
mysqldump error when pushing up a new snapshot

### ISSUE THREAD

**Issue by mustafauysal** [10up/wp-local-docker-v2#97]
**Describe the bug**

It seems there is a problem when pushing up a new snapshot.  
I guess this is related https://bugs.mysql.com/bug.php?id=91640

```
Exporting database...
mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = 'helloworld-test' AND TABLE_NAME = 'wp_commentmeta';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109)
```

It might worth disabling `column-statistics` by default:

```
[mysqldump]
column-statistics=0
```

**Expected behavior**
Pushing up snapshots successfully.

**Environment information**
- MySQL: `5.7.28`

**Additional context**
There is no problem with exporting `10updocker wp db export`

**Comment by dustinrue** [comment]
wpsnapshots was updated recently. Is it still an issue?

**Comment by mustafauysal** [comment]
@dustinrue I'm unable to test, can you follow up with Daine? I guess, he got this error before.

**Comment by Ritesh-patel** [comment]
@dustinrue I recently tried to push a snapshot and had this error.

**Comment by tylercherpak** [comment]
Related PR on wpsnapshots: https://github.com/10up/wpsnapshots/pull/68

**Comment by moraleida** [comment]
Unfortunately this issue is still happening after that PR was merged.

```
❯ 10updocker --version    
WP Local Docker
Version 2.7.0

❯ docker-compose exec phpfpm mysql --version
mysql  Ver 15.1 Distrib 10.3.17-MariaDB, for Linux (x86_64) using readline 5.1

❯ docker-compose exec phpfpm mysqldump --version
mysqldump  Ver 10.17 Distrib 10.3.17-MariaDB, for Linux (x86_64)

```

**Comment by eugene-manuilov** [comment]
@moraleida try to install `2.8.0-rc.15`, it contains the latest version of `wpsnapshots` that has a fix for this issue. Use `npm i -g wp-local-docker@next` command to install the rc version and `10updocker --version` to make sure the version is `2.8.0-rc.15` or higher. Let me know if it helps.

**Comment by moraleida** [comment]
@eugene-manuilov this works, thank you!

**Comment by eugene-manuilov** [comment]
Awesome! We can close this issue then.
