### ISSUE TITLE
Migrating environments between machines without wp-local-snapshots

### ISSUE THREAD

**Issue by samimakela** [10up/wp-local-docker-v2#99]
Is there a way to transfer an environment to another machine (e.g. to another developer) without using wp-local-snapshots? We don't need the database, since we can pull that directly from the staging or production environment.

We love the WP Local Docker and are looking for the best way to implement it into our workflow.

**Comment by dustinrue** [comment]
What I like to do is commit the directory that wp-local-docker generates right into git along with your source files. By keeping everything in git, and using a .gitignore to ignore generated or large files out, you can easily version control your local environments and share them with other team members.

**Comment by samimakela** [comment]
@dustinrue that's what I tried as well, but cloning the repository and running `10updocker start` doesn't do the trick. What additional steps should I take or do the other team members need to first run '10updocker create'

**Comment by dustinrue** [comment]
Make sure you are including the hidden wp-local-docker files, especially .config.json

**Comment by samimakela** [comment]
They are all there and the environment seems to start just fine, but I need to complete the following steps _manually_ before I have WordPress running smoothly:

1) Add the hosts `sudo 10updocker-hosts sitename.test`
2) Creating a database 
3) Download, configure and install WordPress 

So the questions are:

a) Could you confirm that these steps need to be done manually and `10updocker start` is not supposed to do any of these for me? 
b) If so, what's the best way of creating the database via command line?

**Comment by dustinrue** [comment]
This is correct. All of those steps are required. You can create a Makefile to simply the process if you want.

You have some options for creating the database. If you want an empty one, and you store the wp-config.php for local development in the repo, you can simply issue `10updocker wp db create` and then `10updocker wp core install` to install the site. You'll need to run the command with the proper flags. 

The other option, if you use S3/AWS is to setup wpsnapshots which allows you to more easily share databases between team members.

**Comment by samimakela** [comment]
I'm not very familiar with Makefiles, so if you can can point to me to an example that would be awesome. In any case all the advice so far has been super helpful so thank you very much already at this point!

**Comment by tylercherpak** [comment]
Hey all,

This looks to be resolved so I am going to close it out. Feel free to comment and I can reopen the issue if you still have questions! Thanks!
